TODO.md
guide/creating-your-bot/README.md
guide/creating-your-bot/adding-more-commands.md
guide/creating-your-bot/commands-with-user-input.md
guide/creating-your-bot/common-questions.md
guide/preparations/README.md
guide/preparations/adding-your-bot-to-servers.md
guide/preparations/setting-up-a-linter.md
guide/sequelize/README.md
guide/testing/README.md

Some last minute changes to fix dead links and spruce things up a bit.

 Fix dead links, add small extra info, change other small things

---

code_samples/sequelize/currency/currency.js
code_samples/sequelize/currency/dbInit.js
code_samples/sequelize/currency/dbObjects.js
code_samples/sequelize/currency/models/CurrencyShop.js
code_samples/sequelize/currency/models/UserItems.js
code_samples/sequelize/currency/models/Users.js
guide/sequelize/README.md
guide/sequelize/currency.md

Added code samples
Refactored code to code samples
Removed links to other sections on the page
Other minor corrections

Sequelize tutorials cleanup

---

guide/_sidebar.md
guide/sharding/additional-information.md

smol typos

---

guide/assets/css/main.css
guide/index.html

Since consolas doesn't work on macOS or mobile devices (RIP), here's one that looks very similar.

Replace codeblocks font

---

guide/creating-your-bot/common-questions.md

Also made a new mini section for things you can do to configure your bot.

Add some more examples to the FAQ

---

code_samples/sharding/getting-started/bot.js
code_samples/sharding/getting-started/index.js
guide/assets/css/main.css
guide/command-handling/README.md
guide/creating-your-bot/collectors.md
guide/sequelize/currency.md
guide/sharding/README.md

Fixed some inconsistencies around some files where arrow functions with single params had parens, as well as normalized the spacing between headers/codeblocks/paragraphs in the currency file.
Also added some CSS to make list items a bit more spaced out and readable.

Consistency changes

---

guide/additional-info/es6-syntax.md
guide/command-handling/README.md
guide/command-handling/adding-features.md
guide/creating-your-bot/collectors.md
guide/preparations/README.md
guide/preparations/setting-up-a-linter.md

More than 1 letter of changes.

Spelling Fixes

---

TODO.md
guide/_sidebar.md
guide/additional-info/async-await.md
guide/creating-your-bot/common-questions.md

Added Async/Await and Promise explaination and examples aswell as the difference between Users and GuildMembers in faq (you maybe want to look over the grammar 👀 )

 added Async/Await examples and explaination also added difference between Users and GuildMembers in faq

---

guide/additional-info/async-await.md

yea that is the last one *i swear*

just to prevent inconsistency

---

guide/_sidebar.md

"Understand" to "Understanding"

Change async/await sidebar link

---

guide/additional-info/es6-syntax.md
guide/command-handling/adding-features.md
guide/creating-your-bot/README.md
guide/creating-your-bot/collectors.md
guide/creating-your-bot/commands-with-user-input.md
guide/preparations/adding-your-bot-to-servers.md
guide/preparations/setting-up-a-bot-application.md
guide/sequelize/README.md
guide/sequelize/currency.md
guide/sharding/README.md
guide/sharding/additional-information.md

As the title says -- various awkward phrasing occurrences have been adjusted, stylistics changes such as spacing out objects or capitalization, consistency changes and more.
Edit: Also as discussed on Discord so this doesn't get lost: 
killing / restarting a shard needs clarification ( <http://discordjs.guide/#/sharding/additional-information> )

Various phrasing, stylistic and other adjustments

---

guide/additional-info/async-await.md

yea pretty much an enhancement to the async/await page (you want to look over my grammar again btw)

added theory information to async/await aswell as replaced the words function in combination with .then() and .catch() because that are methods

---

guide/creating-your-bot/common-questions.md

Just small small tweaks to the "**What is the difference between a User and a GuildMember?**" part, like "a" vs "an" as well as merging two sentences into a paragraph instead of having three separate sentences with empty lines inbetween.

Fix some little grammar issues and formatting

---

guide/additional-info/async-await.md

because they yelled at me for that 😭

fixes stuff Gus and Appel pointed out (in async/await)

---

TODO.md
guide/sharding/additional-information.md

Reword sharding page for clarity, consistency, and smoother reading.

Sharding page updates

---

guide/additional-info/miscellaneous-examples.md

Somehow overlooked this in my last PR.

Fix malformed link, log full error

---

guide/creating-your-bot/common-questions.md

Since this is a common question, might as well add it here

Adding reacting to bot message example

---

guide/popular-topics/common-questions.md

we usually use the <id> syntax when showing example things to put inside functions, so made this do that as well.

consistency

---

guide/_sidebar.md
guide/requesting-more-content.md

So that people can let us know what they wanna see. 🎉

Add a page explaining how to request content

---

guide/sharding/additional-information.md

Added link to another open-source bot that has sharding and is made with discord.js

Added link to an open-source bot that has sharding

---

README.md
guide/assets/js/main.js
guide/command-handling/README.md
guide/command-handling/adding-features.md
guide/command-handling/dynamic-commands.md
guide/creating-your-bot/README.md
guide/creating-your-bot/adding-more-commands.md
guide/creating-your-bot/commands-with-user-input.md
guide/creating-your-bot/configuration-files.md
guide/index.html
guide/popular-topics/reactions.md
guide/requesting-more-content.md
guide/sequelize/README.md
guide/sequelize/currency.md
guide/sharding/README.md
guide/sharding/additional-information.md

We've become the official guide for discord.js! :tada: As such, we'll be moving the repo to the discord.js organization, and so links that point to the repo will need to be updated.

Update all repo links and readme

---

TODO.md
guide/_sidebar.md
guide/improving-dev-environment/package-json-scripts.md
guide/improving-dev-environment/pm2.md

The following guides have been added:
- package.json scripts
- pm2

Get started with category for improving your dev environment

---

guide/popular-topics/miscellaneous-examples.md

People, from time to time, tend to ask how to allow your commands to be triggered via mention prefix, so I thought I'd add a basic example of how to do that. Also updated the section headers in the misc. examples file since they each had an extra `#`.

Add mention prefix example

---

guide/command-handling/README.md

This is mostly because I realized that when someone links someone else to the command handler page, there's that "This page bases its code off the previous page" message at the top, which leads all the way to the "Up & running" page if you keep clicking it through all the previous chapters.
This isn't really ideal; having the base code on the same page (although identical) makes it much easier to read through that section of the guide.
I've also restructured a bit of the page, cuz some of it was a bit awkwardly placed.

Update initial command handler page for clarity

---

CONTRIBUTING.md
TODO.md

Because the current one is pretty bare-bones and doesn't really let others know that we want things done in a certain manner. Combined with the recent CircleCI integration, this may cut down on the amount of comments we make when reviewing PRs (in certain areas).
Realizing that this is a bit long, I'm on the fence about adding a TL;DR section near the top, which would just be a short list of the things listed with links to the respective sections. If anyone thinks that'd be a good idea, I'd be alright with adding it in.

Add general guidelines to the contributing.md file

---

guide/popular-topics/miscellaneous-examples.md

Update mention prefix example text

---

code_samples/additional-info/rest-api/index.js
guide/additional-info/rest-api.md

random.cat is now aws.random.cat

update REST guide

---

code_samples/sequelize/currency/app.js
code_samples/sequelize/currency/dbInit.js
code_samples/sequelize/currency/dbObjects.js
code_samples/sequelize/tags/sequelize.js
guide/sequelize/README.md
guide/sequelize/currency.md

Updated examples to use updated sequelize operators.

fix sequelize deprecation warnings

---

code-samples/command-handling/adding-features/commands/help.js

There should be some form of error handling I think, even if just for people to get in the habit of properly dealing with errors.

Adding error logging to dm sending failure

---

guide/command-handling/dynamic-commands.md

sympathy - Today at 16:25
> hey uhhhjhh
> whom is in charge of discordjs.guide
> cause theyre's a realy bad error in one of the pages on there
fixed to avert pitchfork armed riots

minor spelling fix to avert global breakdown

---

guide/popular-topics/reactions.md

just what the title says :wink:

fixed broken link to async/await guide

---

guide/_sidebar.md
guide/popular-topics/embeds.md
guide/popular-topics/miscellaneous-examples.md

- add Popular Topics > Embeds
- remove embed content from Misc
- fix typos in Misc
Open for suggestions as always

Feat: own popular topic for Embeds

---

guide/popular-topics/reactions.md

warn people about using undocumented apis

add warning to reactions guide

---

guide/sharding/additional-information.md

Came across this in a support channel the other day and figured it'd be nice to demonstrate.

add async functions to sharding examples

---

guide/_sidebar.md
guide/additional-info/collections.md

Added a page on using Collections. Note that this is not about obvious things like what `map` does or how to pass in a callback function, but on the interface compared to `Array` and notable specific things to `Collection`.
Purposely did not mention deprecated methods (obviously) but also `tap` because of its interface changing in v12.

Add page on Collections

---

guide/preparations/README.md

Hey folks, I noticed you didn't have a paragraph for macOS users to install node so I thought I'd add it. It's basically the same as Windows but users also have the option to use a package manager. Let me know if you want me to add any more info!

Add node installation guide for macOS

---

guide/improving-dev-environment/pm2.md

It's significant and useful enough to warrant a note here I think.

Adding pm2 monit note

---

guide/creating-your-bot/commands-with-user-input.md
guide/preparations/README.md

https://github.com/discordjs/guide/blob/1a2cb598b6460433360834111731639dc87dd0fa/guide/preparations/README.md#L71-L72
https://github.com/discordjs/guide/blob/1a2cb598b6460433360834111731639dc87dd0fa/guide/creating-your-bot/commands-with-user-input.md#L264
They probably was left behind at 26ff47ccf859d2e6e8a451bb45b4ee5eba2cadea and 1a2a145e9ad52e2cdf1b98af3e3377487106ff89.

Fix markup

---

guide/additional-info/changes-in-v12.md

Not complete and not pretty, but it's more stuff to reference

adding some more items to the list

---

guide/additional-info/changes-in-v12.md

Rewrite the intro to include new requirements (Node v10, current repo for v12), include a section on commonly-used methods and properties that changed from v11 -> v12.

V11 vs v12

---

guide/requesting-more-content.md

sharding is hyperlinked so why not the miscellanous examples page too

hyperlink the miscellanous example page

---

guide/sequelize/README.md

This PR fixes a typo in the page "Storing data with Sequelize"

Fixed a typo.

---

guide/additional-info/changes-in-v12.md

Updated commonly-used methods section to add collection#find and other changes, and a comprehensive section update for:
* EvaluatedPermissions
* Game
* GroupDMChannel
* Guild
* GuildChannel
* GuildMember
* HTTPError
* Integration
* Invite
* Message
* MessageReaction
* OAuth2Application
* PartialGuild
* PartialGuildChannel
* PermissionOverwrite
* Permissions

Master list changes

---

guide/additional-info/changes-in-v12.md

Continue class changes up to and including Role, as well as going back through previously-done classes for missed changes, noting properties that are now getters in v12, and some typos that needed to be fixed (oberwrite is not a word according to the red squiggly line).
I also went back through and added reasons for changes and deletions to the best of my ability.  Also included are explanations of new classes, methods and properties.

Class changes, deletions and additions through Role, other cleanup

---

guide/sharding/additional-information.md

I fixed your asynchronous code of the broadcastEval() because it didn't work like this.

fixed code

---

guide/popular-topics/embeds.md

- Remove mention of base 10 where other ints are valid as well
- change the mentioned color in the text to be consistent with the example
- add explanations for method chaining and resending
- slight wording improvements for easier to comprehend semantics

embed page update

---

guide/additional-info/changes-in-v12.md
guide/popular-topics/common-questions.md
guide/popular-topics/reactions.md

`guild.channels.find('name', 'welcome-messages')` no longer works. Therefore, I updated it to use the newer function method

Fix recommending of old method

---

guide/additional-info/changes-in-v12.md

This PR documents what I believe to be the most important changes to voice.

Add voice changes in v12

---

guide/creating-your-bot/commands-with-user-input.md
guide/popular-topics/collectors.md
guide/popular-topics/common-questions.md
guide/popular-topics/embeds.md
guide/popular-topics/miscellaneous-examples.md
guide/popular-topics/permissions.md
guide/preparations/README.md

Update methods and properties in the guide to correct v12 syntax.
Update Node required version.

Misc updates

---

guide/additional-info/changes-in-v12.md

Add a table of contents, fix hyperlinks, update class changes that were reverted.

Fix links, PermissionOverwrite changes

---

guide/improving-dev-environment/pm2.md

The old link isn't available, so I have tried to find an appropriate documentation - Not the best, but better than a 404-Page ¯\_(ツ)_/¯

Corrected Link

---

guide/popular-topics/embeds.md

Move the warning so it is more visible, i didnt saw it for the first time when i read the guide

Move the warning so it is more visible

---

guide/preparations/setting-up-a-bot-application.md

The creating a bot steps has changed a little, so I updated it.
As for the screenshot, there is a few change in the layout, but I didn't take it well, so I didn't updated

Update creating bot steps

---

guide/popular-topics/common-questions.md

Per #265
Note changes on fetchMembers() -> members.fetch()
and return guild -> return members collection

Frontport examples to V12-changes

---

code-samples/command-handling/adding-features/11/commands/reload.js
code-samples/command-handling/adding-features/12/commands/reload.js
guide/command-handling/adding-features.md

Adds a guide on creating a command to reload commands.

Add guide on reloading commands

---

guide/additional-info/rest-api.md

The guide says it's going to make use of destructuring, so we should also be destructuring what we want from the library.

Destructure the d.js lib

---

guide/additional-info/rest-api.md

#283 Left broken tip component, this fixes it.

Fix broken tip after recent PR

---

guide/popular-topics/miscellaneous-examples.md

Use play instead of playStream for master branch code

---

guide/preparations/setting-up-a-linter.md

Some of the wording in the section about choosing a code editor was a bit awkward; this PR aims to clean it up.

Style changes

---

guide/.vuepress/sidebar.js
guide/popular-topics/errors.md

This PR adds a section on how to diagnose errors, different types of errors, and some common errors, it is HEAVILY experimental, all feedback is appreciated, i am not quite sure how to structure this, so if you have ideas please comment them. ~~For right now, websocket errors are not included, but they could possibly be added to fulfil #195~~ Websocket errors are partially added. This section is planned to fulfil https://github.com/discordjs/guide/projects/1#card-16181091

Add error section

---

guide/popular-topics/reactions.md

This PR adds a topic to the reactions page focusing on how to remove reactions. it talks about:
- removing all reactions
- removing reactions by emoji
- removing reactions by user
in accordance with https://github.com/discordjs/guide/projects/1#card-16181089

Add topic to reactions page about removing reactions

---

guide/popular-topics/webhooks.md

Fixes an oopsie in the webhook section

Fix oopsie doopsie in webhook guide

---

guide/additional-info/changes-in-v12.md

This PR fixes some markdown, extra backslashes where not needed

fix markdown

---

code-samples/miscellaneous/parsing-mention-arguments/12/index.js
code-samples/popular-topics/canvas/12/index.js
code-samples/popular-topics/permissions/12/index.js
guide/additional-info/changes-in-v12.md
guide/miscellaneous/parsing-mention-arguments.md
guide/popular-topics/canvas.md
guide/popular-topics/common-questions.md
guide/popular-topics/permissions.md
guide/popular-topics/reactions.md
guide/sharding/README.md

This PR refactors master code to account for the upcoming master changes highlighted in https://github.com/discordjs/discord.js/pull/3696. 
- ~~see what the heck is going on with Sharding code samples and change them.~~

Refactor master code samples for upcoming master Manager changes

---

guide/additional-info/async-await.md
guide/commando/README.md
guide/popular-topics/common-questions.md
guide/popular-topics/errors.md
guide/popular-topics/permissions.md
guide/sharding/README.md
guide/sharding/extended.md

This PR adds various branch tags to support v12 code

add more branch tags to support v12 code

---

guide/additional-info/changes-in-v12.md
guide/popular-topics/canvas.md

This PR fixes some typos in the changes for v12 section
this PR also fixes #326

fix(grammar): various typos

---

guide/popular-topics/common-questions.md

This PR was made to correct the wording of adding and removing roles in the guildMemberUpdate event example.

fix wording

---

guide/creating-your-bot/commands-with-user-input.md
guide/miscellaneous/parsing-mention-arguments.md
guide/popular-topics/canvas.md
guide/popular-topics/common-questions.md
guide/popular-topics/embeds.md
guide/popular-topics/permissions.md
guide/popular-topics/reactions.md
guide/popular-topics/webhooks.md
guide/sharding/README.md
guide/sharding/additional-information.md
guide/sharding/extended.md

This PR adds some more branch tags (some that i may have missed in my previous PR), specifically for the new managers commit, adding .cache in various places missed in @RDambrosio016's PR
also fixes some typos along the way
MessageReaction#fetch fetches the message the reaction belongs to, and updates the reaction using that data, so there is no need to fetch both the reaction, and the message seperately, ~~(it currently doesn't update the existing message if its a partial, i made a PR https://github.com/discordjs/discord.js/pull/3789 to fix this however)~~ pr was merged
(reference for only displaying the warning about the color not being resolved on v11 https://github.com/discordjs/discord.js/commit/52bc5b0170e2902 …

feat/fix: more branch tags + some typos

---

guide/commando/args.md
guide/commando/client-values.md

Updated the Commando guide to v12. Unsurprisingly, not much to change.

fix: Update Commando guide to v12

---

guide/miscellaneous/parsing-mention-arguments.md
guide/popular-topics/permissions.md
guide/popular-topics/reactions.md
guide/sharding/README.md
guide/sharding/extended.md

Recent #328 left new inline branch tags without inline property, causing them to not display as inline. This fixes those.

Fix inline branch tags

---

guide/additional-info/changes-in-v12.md
guide/commando/README.md
guide/preparations/README.md

Fairly self explanatory, guide should not state improper nodejs requirement. Minimum required nodejs version is changed from 10.X in the guide about updated to djs V12 to 12.x
edit: Also changing install instruction since V12 is now standard release

Update required node version to V12 & npm install command

---

guide/additional-info/changes-in-v12.md

There is only one change to include proper syntax for sending files.

fix Syntax for sending files with name

---

code-samples/keyv/config.json
code-samples/keyv/index.js
guide/keyv/README.md

Resulting code and code sample for the keyv guide section as per user request (on discord)

feat: keyv guide resulting code

---

guide/additional-info/changes-in-v12.md

Remove no longer needed descriptions about v12

Remove descriptions no longer need

---

guide/additional-info/changes-in-v12.md

* mark full section as addition on TextbasedChannel#send

chore: fix md formatting in update guide

---

guide/popular-topics/audit-logs.md

> Note that we will also make the function async to make use of await. As well we will **make sure to ignore DMs**.
The provided code did not actually ignore DMs, now it does

fix: ignore DM in audit log example

---

guide/additional-info/changes-in-v12.md

* document GuildChannel#createOverwrite
* fix GuildChannel#updateOverwrite (remove additional s)
* document GuildChannel#overwritePermissions
* fix GuildChannel#replacePermissionOverwrites to be renamed instead of deleted

fix(v12-changes): permission related updated

---

guide/popular-topics/intents.md

This PR creates another article for the Discord.js guide covering [Gateway Intents](https://github.com/discord/discord-api-docs/issues/1363), what they do and how to use them.

feat: Gateway Intents article

---

guide/.vuepress/sidebar.js
guide/popular-topics/intents.md

* add intents to sidebar
* add clarifying comment
* fix heading nesting

fix: add intents to sidebar and apply structural changes

---

guide/additional-info/changes-in-v12.md

- Adds a small change to a code block to make the diff one look more "correct"
- Spelling changes 
- Event names fixed

chore: Minor tweaks

---

guide/additional-info/changes-in-v12.md
guide/popular-topics/webhooks.md

Updates content with v11 -> v12 changes to webhooks.

Update webhook-related content with v12 changes.

---

guide/preparations/adding-your-bot-to-servers.md

**Changes made by this PR**
Updated site URLs from discordapp.com to discord.com.

URL update

---

guide/sequelize/currency.md

Fixes a small grammar mistake I noticed on the Sequelize currency system page. Nothing too major.

Update Sequelize currency system guide

---

guide/popular-topics/audit-logs.md
guide/popular-topics/embeds.md

3 inline fields display regardless if a thumbnail is set

fix(embeds): remove outdated embed note

---

guide/popular-topics/permissions.md

added new section on permissions.md about displaying permissions flags

add section about converting Permissions into flags

---

guide/popular-topics/common-questions.md

Adds unban example under common questions #474, formerly #489

Added how to unban user section

---

guide/popular-topics/intents.md

Updates the tips regarding how the privileged intents work now that they've gone live and we have a better understanding of them.

fix: Tips regarding Intents

---

guide/additional-info/changes-in-v12.md
guide/command-handling/adding-features.md
guide/creating-your-bot/commands-with-user-input.md

implements #449 (stale) across the guide.

fix: avatar URL sizes

---

guide/additional-info/async-await.md
guide/additional-info/changes-in-v12.md
guide/additional-info/es6-syntax.md
guide/additional-info/rest-api.md
guide/commando/README.md
guide/creating-your-bot/commands-with-user-input.md
guide/improving-dev-environment/package-json-scripts.md
guide/miscellaneous/parsing-mention-arguments.md
guide/oauth2/README.md
guide/popular-topics/collectors.md
guide/popular-topics/errors.md
guide/popular-topics/partials.md
guide/popular-topics/reactions.md
guide/preparations/adding-your-bot-to-servers.md
guide/preparations/setting-up-a-bot-application.md
guide/sequelize/currency.md
guide/sharding/README.md
guide/sharding/extended.md
guide/voice/optimisation-and-troubleshooting.md
guide/voice/understanding-voice.md
guide/voice/voice-broadcasts.md

various typos, grammar fixes and consistency changes

fix(*): various typos

---

guide/additional-info/changes-in-v12.md

improves accuracy of the #toString description in v12-changes

feat: improve accuracy on toString changes

---

guide/additional-info/changes-in-v12.md

Fixes a typo that has been introduced with #500

fix(changes-in-v12): typo

---

CONTRIBUTING.md
code-samples/commando/getting-started/index.js
code-samples/sharding/extended/11/bot.js
code-samples/sharding/extended/12/bot.js
code-samples/sharding/getting-started/11/bot.js
code-samples/sharding/getting-started/12/bot.js
guide/additional-info/es6-syntax.md
guide/additional-info/rest-api.md
guide/commando/README.md
guide/creating-your-bot/commands-with-user-input.md
guide/improving-dev-environment/package-json-scripts.md
guide/miscellaneous/useful-packages.md
guide/popular-topics/embeds.md
guide/popular-topics/errors.md
guide/popular-topics/intents.md
guide/popular-topics/permissions-extended.md
guide/popular-topics/permissions.md
guide/preparations/adding-your-bot-to-servers.md
guide/preparations/setting-up-a-bot-application.md
guide/sequelize/currency.md
guide/sharding/README.md
guide/sharding/additional-information.md
guide/voice/receiving-audio.md
guide/voice/understanding-voice.md

Fixes various typos across a lot of pages and also changes any `client.login('token')` or alike instances to `client.login('your-token-goes-here')`.

fix(*): Various typos and consistency changes

---

guide/sharding/additional-information.md

Bastion is no longer open source.
See: https://github.com/TheBastionBot/Bastion/issues/890

Remove Bastion example

---

guide/sequelize/README.md

:P
:') fixed a very *very* small typo

Fix tiny typo

---

guide/miscellaneous/parsing-mention-arguments.md

Just found a quick spelling mistake, so edited the page and pull requested it 👍

Fixed a spelling mistake i found :)

---

guide/popular-topics/faq.md

Adds quick answer for how to block user(s) from using a bot, including a quick tip on how to utilize database for that.
Closes #460

Add FAQ for user blocking

---

guide/miscellaneous/useful-packages.md

Line 58 caused a syntax error.
Changed the period (.) to a comma (,).

Minor correction on line 58.

---

code-samples/command-handling/adding-features/11/index.js
code-samples/command-handling/adding-features/12/index.js
guide/command-handling/adding-features.md

This PR fixes a typo in advanced command handling for permissions.

fix: message.channel.reply is not a function

---

guide/preparations/setting-up-a-bot-application.md

⚠️ (finally) closes #100 
- show token examples from a reset test application to make mistakes more obvious
- add a section about environment variables
- add a section about git and `.gitignore`
- add a small notice about hosting service's ways to securely store keys

feat(preparations): token security and env vars

---

guide/command-handling/adding-features.md

⚠️ closes #564
Increase verbosity in the cooldown guide, explaining how the collections key/value relation are structured and why. This should now give a better understanding of the inner workings, rather than just providing the necessary code.

feat(adding-features): increase verbosity of cooldown section

---

guide/commando/README.md

docs(Commando): Update installation instructions

---

guide/preparations/README.md

(You can use `cd`  and `mkdir` on macOS as well)

Add directory-creating/-switching for MacOS

---

guide/additional-info/rest-api.md

fix: bot message not rendering correctly in urban dict cmd

---

guide/preparations/setting-up-a-linter.md

I (think I) found a grammar error in the linter-docs:
> It advisable to … 
-> It‘s advisable to…

Fix grammar error

---

guide/improving-dev-environment/pm2.md

Update broken pm2 docs link

---

guide/popular-topics/faq.md

Changes "bots" to "bot's" and changes "How to" to "How do I".

Fix grammar

---

code-samples/sharding/extended/11/bot.js
code-samples/sharding/extended/12/bot.js
guide/sharding/additional-information.md
guide/sharding/extended.md

Fixes #620 and improves on the practices in the code a bit.

fix(sharding): sharding guide overhaul

---

code-samples/command-handling/adding-features/11/commands/utility/reload.js
code-samples/command-handling/adding-features/12/commands/utility/reload.js
guide/command-handling/adding-features.md

~~Déjà vu #359~~
This fixes reloading commands when someone passes an alias instead of the command name.

fix: reloading commands via alias

---

code-samples/sequelize/tags/sequelize.js
guide/sequelize/README.md

Fixes incorrect SQL in the comments of Sequelize guides.

Fix SQL query examples on Sequelize guides

---

guide/sharding/README.md

Add a tip that educates the user on the existence and usage of Internal Sharding (see #guide-discussion).

Add Internal Sharding

---

guide/commando/README.md

This PR should be merged because it contains new install instructions for v11, v12 and master branch

Fixed install instructions

---

guide/additional-info/async-await.md
guide/additional-info/es6-syntax.md
guide/additional-info/rest-api.md
guide/commando/first-command.md
guide/miscellaneous/parsing-mention-arguments.md
guide/miscellaneous/useful-packages.md
guide/popular-topics/audit-logs.md
guide/popular-topics/collectors.md
guide/popular-topics/errors.md
guide/popular-topics/faq.md
guide/popular-topics/reactions.md
guide/sequelize/README.md
guide/sequelize/currency.md
guide/sharding/README.md
guide/sharding/extended.md
guide/voice/optimisation-and-troubleshooting.md
guide/voice/the-basics.md
guide/voice/understanding-voice.md

This PR normalizes sentence structures the use "we"/"our"/"us"/etc. in favor of "you"/"your"/"the relevant item" format, as is [mentioned in our contributing guidelines](https://github.com/discordjs/guide/blob/master/CONTRIBUTING.md#spelling-grammar-and-wording).

fix(*): "We"/"our"/etc. to "you"/"your"/etc.

---

guide/preparations/adding-your-bot-to-servers.md

This adds the `applications.commands` scope to adding-your-bot-to-servers page, to ensure users don't get hit with errors when attempting to create Slash Commands.

chore: update adding-your-bot to include commands scope

---

guide/miscellaneous/useful-packages.md

Resolves #682.
[Demo](https://deploy-preview-685--discordjs-guide.netlify.app/)
This PR replaces the mutable `moment.js` package with the immutable `Day.js` package in the `Useful packages` section in the guide. The goal of this PR is to make sure developers can use the more secure module without the vulnerabilities that `moment.js` has.
**Status**

feat(useful-packages): Replace `moment.js` with `Day.js`.

---

guide/preparations/README.md
guide/preparations/setting-up-a-linter.md

[Demo](https://deploy-preview-696--discordjs-guide.netlify.app/preparations/)
This PR updates the `Preparations` section of the guide for the `v13` release.
**Status**
Please let me know if there is more to change. I'll be happy to work on them.

feat: v13 `preparations`.

---

guide/popular-topics/collectors.md

Figured I might as well get started on some updates - this updates the Collectors page to bring it in line with v13, and adds a section on interaction collectors.

feat: v13 collectors

---

guide/.vuepress/sidebar.ts
guide/popular-topics/threads.md

This PR adds a page to the popular topics section, documenting the usage of threads within djs.

feat: threads

---

guide/command-handling/README.md

Should be "interaction" instead of "interacton". Basically, this fixes the typo.

fix(CommandHandling): small typo at code block

---

code-samples/popular-topics/permissions/13/index.js
guide/popular-topics/permissions-extended.md
guide/popular-topics/permissions.md

[Demo](https://deploy-preview-705--discordjs-guide.netlify.app/popular-topics/permissions.html)
This PR updates the `Permissions` section of the guide for the `v13` release.
**Status**
Please let me know if there is more to change. I'll be happy to work on them.

feat: v13 `Permissions`.

---

code-samples/popular-topics/webhooks/13/using-Webhook.js
code-samples/popular-topics/webhooks/13/using-WebhookClient.js
guide/popular-topics/webhooks.md

[Demo](https://deploy-preview-700--discordjs-guide.netlify.app/popular-topics/webhooks.html)
This PR updates the `Webhooks` section of the guide for the `v13` release.
**Status**
Please let me know if there is more to change. I'll be happy to work on them.

feat: v13 `Webhooks`.

---

guide/miscellaneous/useful-packages.md

This updates some code samples in the useful packages page to use v13 syntax(es), for example, message collectors or interactions. Additionally, certain GitHub links have outdated usernames so that is changed, too (even if GH auto redirects you anyway 🤷‍♂️).

feat: update useful packages guide for v13

---

guide/popular-topics/embeds.md

feat: v13 embeds

---

guide/popular-topics/faq.md

_(Split from #708)_
[Demo](https://deploy-preview-720--discordjs-guide.netlify.app/popular-topics/faq.html)
This PR updates the `FAQ` section of the guide for the `v13` release.
**Status**
Please let me know if there is more to change. I'll be happy to work on them.

feat: v13 `FAQ`.

---

guide/interactions/registering-slash-commands.md

As requested by Crawl, I have taken the deploy script from Yuu v3 and adapted it to commonJS (yuck), and added it as an advanced deployment section to the registering page so that it may  be used in conjunction with the modular slash command handler provided by the guide.

feat(interactions): advanced deployment

---

guide/.vuepress/sidebar.ts
guide/additional-info/changes-in-v13.md

This is by no means a complete guide on upgrading from v12 to v13, but the page needs to start somewhere.
Others are welcome to contribute directly to this PR, or build upon this page if/when it's merged.
Replaces #551 as a proper feature branch so I can rebase it
---
✏ currently includes changes up until https://github.com/discordjs/discord.js/commit/4886ae2

feat: v13 changes guide

---

guide/interactions/slash-command-permissions.md

Closes #748
This PR adds a tip for global commands for the `Slash command permissions` section of the guide.

feat: Add tip for global commands.

---

guide/sequelize/README.md

Fixed `if (e.name === "SequelizeUniqueConstraintError")` to be consistent with the snippet in the code block, which is `if (error.name === 'SequelizeUniqueConstraintError')`.
Also fixed a grammar error that unnecessarily capitalized "on" in the middle of a sentence.

fix: consistency in Sequelize delta section

---

guide/additional-info/changes-in-v13.md
guide/preparations/README.md

Basing this on https://github.com/discordjs/discord.js/commit/a56ba097dce5b476939a10d6dc9250a966356594.

fix(*): bump the required Node.js version

---

guide/additional-info/changes-in-v13.md

Just another update to the v13 changes page that weren't included when the PR was merged.

feat: more v13 changes

---

guide/additional-info/es6-syntax.md

I have removed the double dot, making it match javascript syntax

fix: interaction..reply() > interaction.reply()

---

CONTRIBUTING.md
guide/.vuepress/components/DocsLink.vue

This PR changes instances of `master` to `main`

chore: change master to main

---

guide/additional-info/changes-in-v13.md

This fixes an issue in the LimitedCollection constructor where a number was used instead of an object

fix(v13-changes): LimitedInteraction constructor

---

.github/workflows/test.yml

This makes use of Node 16 to be uniformed with the main repository.

workflows(Test): upgrade Node version to 16.x

---

guide/additional-info/changes-in-v13.md

feat: list of changed id properties

---

guide/popular-topics/faq.md

This updates the code to use v13 syntax.

fix(FAQ): update setPresence syntax sample

---

code-samples/command-handling/file-setup/13/commands/avatar.js
code-samples/command-handling/file-setup/13/commands/beep.js
code-samples/command-handling/file-setup/13/commands/kick.js
code-samples/command-handling/file-setup/13/commands/options-info.js
code-samples/command-handling/file-setup/13/commands/ping.js
code-samples/command-handling/file-setup/13/commands/prune.js
code-samples/command-handling/file-setup/13/commands/server.js
code-samples/command-handling/file-setup/13/commands/user-info.js
guide/command-handling/README.md
guide/interactions/registering-slash-commands.md
guide/interactions/slash-command-permissions.md

This PR refactors parts of the interactions and command handler sections:
- command handling uses builders to ease the deployment steps
- deployment has been refactored to use @discordjs/rest entirely and not rely on other methods
- command permissions no longer showcase the messageCreate event

refactor: refactor command deployment & command handling

---

guide/interactions/registering-slash-commands.md

The old one leads to a 404. This one fixes it.

fix(Interactions): update outdated link to Discord developer docs

---

code-samples/command-handling/file-setup/13/index.js

Setting command names wasn't working before getting an undefined error for each command,  thanks  ovxrfl0w#1337 on Discord they  noticing this while helping me

Fix command names set

---

guide/additional-info/changes-in-v13.md

A curly bracket was missing in the change, as there are two opening-brackets yet only one closing bracket

fix: add missing `}` in diff

---

guide/creating-your-bot/adding-more-commands.md

Replaces removed property `guild.region` with `guild.verificationLevel`.

fix(creating-your-bot): Replace `guild.region` with `guild.verificationLevel`.

---

guide/preparations/README.md

This PR moves the warning related to the required Nodejs version for `discord.js v13` a little above to the top of the page so that the user get to know about it sooner. It also improves some installation instructions by changing a few words here and there.

refactor(preparations): improve instructions for installing node and djs

---

guide/popular-topics/faq.md

Update Ping Example

---

guide/additional-info/changes-in-v13.md
guide/additional-info/rest-api.md
guide/creating-your-bot/README.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/creating-commands.md
guide/improving-dev-environment/package-json-scripts.md
guide/improving-dev-environment/pm2.md
guide/interactions/registering-slash-commands.md
guide/keyv/README.md
guide/popular-topics/builders.md
guide/popular-topics/canvas.md
guide/popular-topics/faq.md
guide/preparations/README.md
guide/preparations/setting-up-a-linter.md
guide/sequelize/README.md
guide/sharding/additional-information.md
guide/voice/README.md

[Demo](https://deploy-preview-840--discordjs-guide.netlify.app/)
This PR adds alternative `yarn` and `pnpm` commands along with the existing `npm` commands for users using other package manager.
Also makes the use of `no line numbers` consistent for terminal commands.
Some parts are modified where necessary.
**Status**
- Setting up a bot application.¹
- Adding your bot to a server.¹
- Event handling.¹
- Replying...¹
- Permissions.¹
- Buttons.¹
- Select Menus.¹
- Threads.¹
- Embeds.¹
- Reactions.¹
- Collectors.¹
- Permissions.¹
- Permissions (extended).¹
- Gateway Intents.¹
- Webhooks.¹
- Errors.¹
- Audit logs.¹
- Sharding¹
- Notation.¹
- ES6 Syntax.
- Collections.¹
- Async/Await.
**Reference**
¹ Does not require …

feat: More package managers! `yarn` and `pnpm` support!

---

guide/additional-info/async-await.md
guide/popular-topics/reactions.md

Changed all `interaction.reply(string, { fetchReply: true })` => `interaction.reply({ content: string, fetchReply: true })`
Changed `replyMessage.delete({ timeout: 10000 })` => `setTimeout(() => replyMessage.delete(), 10000)`

fix: outdated code in async-await section and reactions page

---

guide/popular-topics/threads.md

Updates the page on `Threads`.
- `private_thread` -> `GUILD_PRIVATE_THREAD`
- Updated outdated info about public threads.
- Updates links to Docs.

feat: Update outdated `Threads` page.

---

code-samples/creating-your-bot/command-handling/deploy-commands.js
code-samples/creating-your-bot/creating-commands/deploy-commands.js
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/creating-commands.md

Refactored the existing async/await IIFE to use a simpler promise chain instead, increasing readability and reducing complexity for newer users who might not be familiar with IIFEs or async/await/try/catch syntax.
This PR replaces some code that used unnecessarily complex code with a much simpler promise chain that is much clearer and easier to follow, in place of the existing async IIFE.
This change shouldn't affect the functionality and I've tested it to ensure it works when used, it's a semantics/syntax change to improve readability modifying functionality.

Refactored deploy-commands to use promise chains.

---

guide/popular-topics/canvas.md

This comment previously said "Since the image takes time to load, you should await it," but that's not what await actually does - I changed it to be more accurate.

Make await explanation accurate

---

guide/popular-topics/builders.md

This uses the correct parameters for the hyperlink builder. Original credit goes to Jiralite for finding this bug.

fix(popular-topics): use correct parameters for the hyperlink builder

---

guide/improving-dev-environment/package-json-scripts.md

- Add a teaser about pre/post/lifecycle scripts and a link to the official npm documentation for more information.
- Add a newline after the tip element

feat(package-scripts): link to official docs

---

guide/sharding/README.md

Fixes typo "inter**at**ion" to "inter**act**ion".

fix(sharding): "interaction" typo

---

guide/creating-your-bot/README.md

Changes capitalisation from "docker" to "Docker".  
https://www.docker.com/legal/trademark-guidelines

fix(creating-your-bot): change Docker capitalisation

---

guide/popular-topics/errors.md

This PR is a minor change and Fixes the capitalisation of the abbreviations of "dms" (now "DMs") in lines 195 and 198.

Capitalisation fixture

---

guide/popular-topics/embeds.md

Updating Embed Guide to show new usage of .setAuthor() method.

Updating Embed Guide

---

guide/README.md

Update Codecademy's course link

updating the codecademy's link

---

LICENSE

Another year, another bump. Bumps the license year to 2022!

chore: bump LICENSE year

---

code-samples/creating-your-bot/command-handling/index.js

fix: inconsistency between guide and code-samples

---

code-samples/sequelize/tags/sequelize.js

This fix the typo "descrption" to "description".

fix(sequelize): typo

---

guide/additional-info/changes-in-v13.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/creating-commands.md
guide/interactions/registering-slash-commands.md
guide/voice/README.md
guide/voice/life-cycles.md
guide/whats-new.md

The old links point to archived repositories

chore: update links

---

guide/interactions/registering-slash-commands.md

Subcommands is not part of Choices

---

code-samples/sequelize/currency/13/app.js
code-samples/sequelize/tags/sequelize.js
guide/sequelize/README.md
guide/sequelize/currency.md

This PR removes the usage of Greek alphabets which is confusing for many readers and is inconsistent with the rest of the guide.
Resolves #965.
**Status**

feat: Fix code style inconsistency in the Sequelize pages!

---

guide/whats-new.md

feat: replaces PR link with sapphire guide link

---

guide/additional-info/changes-in-v13.md

Update the old link as the page is now merged

fix: update old link

---

guide/additional-info/rest-api.md

patch(rest-api): code block highlighting

---

guide/popular-topics/errors.md

- Made some stylisation changes for consistency
- Referenced our documentation for error codes instead of the source code
- Updated how one gets their token from the developer portal
- Corrected `MessageEmbed.addFields()` to `MessageEmbed#addFields()`. The former indicates a static method of the class!
- Added the `GUILD_MEMBERS` intent as a possible reason for not receiving members in time

refactor(errors): Update page

---

guide/popular-topics/embeds.md

fix(docs): update embed limits link

---

code-samples/popular-topics/reactions/13/awaiting-reactions.js
code-samples/popular-topics/reactions/13/basic-reacting.js
guide/popular-topics/collectors.md

fix: replace old interaction.reply code

---

guide/whats-new.md

On August 31, 2022, access to message content will become a Privileged Intent
seen on https://support-dev.discord.com/hc/en-us/articles/4404772028055

new privileged intent August 31, 2022** not april

---

guide/popular-topics/faq.md

Replaces the old interaction link with the correct one as per bought in guide-discussion

fix(faq): replace old link

---

package-lock.json
package.json

Changed babel-eslint to @babel/eslint-parser because it's deprecated

Changed babel-eslint to @babel/eslint-parser

---

guide/popular-topics/canvas.md

Before:
After:
***
Before:
After:

fix(canvas): codeblock highlight

---

guide/.vuepress/sidebar.ts
guide/interactions/context-menus.md

Co-authored-by: Ben  <88249114+BenjammingKirby@users.noreply.github.com>
Adds context menu page
Renaming branches apparently closes the PR so I make a new one

feat: add context menu

---

guide/interactions/slash-commands.md

Adds the section to set the new default slash command permissions on the time of registering the commands.

feat(slashcommands): add slash command permissions section

---

code-samples/popular-topics/webhooks/13/using-Webhook.js

client.channels.get is now client.channels.cache.get

fix(code-samples): outdated code

---

.eslintrc.js

Error on indentation instead of the previous warn

chore(eslint): error on indentation

---

guide/interactions/context-menus.md

'user' doesnt work and it confuse me 😭
cause 	.setType('USER'); doesnt work

change 'USER' to 2

---

guide/additional-info/changes-in-v14.md

fix(additional-info): code sample

---

guide/popular-topics/intents.md

fix(intents): code sample

---

guide/additional-info/notation.md
guide/popular-topics/canvas.md
guide/popular-topics/permissions.md
guide/popular-topics/threads.md
guide/popular-topics/webhooks.md
guide/preparations/README.md
guide/sequelize/README.md
guide/sharding/extended.md

- Some changed in v14 were missed in #1146, this PR adds those changes

feat(*): apply v14 changes (#1146 follow-up)

---

code-samples/popular-topics/reactions/14/awaiting-reactions.js
guide/popular-topics/reactions.md

use correct intent

---

guide/interactions/modals.md

It has a spelling mistake. You wrote recieved instead of received.

changed spelling mistake

---

.eslintrc.js
guide/popular-topics/canvas.md

- Fixes warnings from the `no-trailing-spaces` ESLint rule
- Modifies `no-trailing-spaces` to always error
- Miscellaneous changes to the text (capitalisation)

chore(canvas): Fix errors and miscellaneous things

---

guide/creating-your-bot/README.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/creating-commands.md
guide/interactions/autocomplete.md
guide/interactions/buttons.md
guide/interactions/context-menus.md
guide/interactions/modals.md
guide/interactions/select-menus.md
guide/interactions/slash-commands.md
guide/popular-topics/intents.md

This is a general work-in-progress that started as an attempt to add a bit more exposition to sections of the guide, and explain the reasoning behind why things are done a certain way. Other changes are just consistency and filling in gaps that I came across along the way.
Open to feedback and thoughts from others as to similar changes they might want to see - still a draft for now.

feat: More explanations and content

---

guide/interactions/slash-commands.md

Just change highlight lines
bc now its doing it where it doesn't have to be

change highlight lines

---

guide/interactions/autocomplete.md
guide/interactions/buttons.md
guide/interactions/context-menus.md
guide/interactions/slash-commands.md

This PR aims to address the concerns brought up in #1147.

fix(examples): Improve examples

---

guide/popular-topics/intents.md

This PR fixes a typo in the Intents guide.

fix(Intents): typo on intents guide

---

guide/interactions/modals.md

Fix typo in modals.md

---

guide/interactions/modals.md

L128:7 sibmissions to submissions

Typo fix from sibmissions to submissions

---

guide/interactions/modals.md

📝 There is a mistake on the name of the class `ModalSubmitInteraction`.

ModalSubmtInteraction -> ModalSubmitInteraction

---

guide/additional-info/changes-in-v14.md
guide/interactions/autocomplete.md
guide/interactions/modals.md
guide/popular-topics/intents.md

[#8328](https://github.com/discordjs/discord.js/pull/8328)

chore(Interactions): remove interaction typeguards removal

---

guide/additional-info/changes-in-v14.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/creating-commands.md
guide/creating-your-bot/deleting-commands.md
guide/interactions/slash-commands.md
guide/popular-topics/builders.md
guide/popular-topics/threads.md
guide/sequelize/currency.md

chore: Update guide to 14.3.0

---

guide/additional-info/changes-in-v14.md
guide/popular-topics/faq.md

> Yeah i know it will be merged when 14.4.0 is released

Forum channels

---

guide/popular-topics/faq.md

It's better to use `UserManager#send()` instead of fetching the user and then use `User#send()`.

fix: use `UserManager#send()` for sending a DM

---

code-samples/sequelize/currency/14/app.js
guide/sequelize/currency.md

fix(currency): define standalone helper functions

---

guide/.vuepress/sidebar.ts
guide/miscellaneous/cache-customization.md

Fixes #1196. Purposely left out some more advanced usages to not encourage people to go too crazy.

feat(misc): add cache customization guide

---

guide/slash-commands/parsing-options.md

I thought I had written this section in my previous PR, but I must have missed it.
Just a small snippet to address frequent confusion I see around options with choices, to address misunderstandings that the handling would somehow be different.
Also fixed highlighting in the other snippet on the page.

feat: guide on parsing choices

---

guide/creating-your-bot/slash-commands.md
guide/popular-topics/audit-logs.md
guide/slash-commands/advanced-creation.md

Updates two typos present in `advanced-creation.md`

fix: update typos

---

guide/popular-topics/intents.md

This PR fixes the name of the error in the intents page.

fix: update error name

---

code-samples/additional-info/rest-api/14/index.js
code-samples/oauth/simple-oauth-webserver/index.js
guide/additional-info/rest-api.md
guide/oauth2/README.md

fix: use `request.body.json()`

---

guide/creating-your-bot/command-handling.md

The Resulting Code button sends to the wrong link!
Fixed it and changed it to Command Handling resulting code

Fixed the wrong URL at Resulting Code

---

guide/.vuepress/components/DocsLink.vue

fix: add other sections to DocsLink

---

guide/slash-commands/response-methods.md

You can delete ephemeral messages now.

fix: remove incorrect warning

---

guide/creating-your-bot/command-handling.md

Addresses #1317, though it would still be better to have full TypeScript code snippets in future.

feat: additional notes for TypeScript users

---

guide/creating-your-bot/command-deployment.md

Minor typo

---

guide/popular-topics/faq.md

fix(faq): incomplete code in tip

---

code-samples/additional-info/rest-api/14/index.js

There's a mistake at the Rest API code sample.

fix(code-sample): should be editReply

---

guide/slash-commands/advanced-creation.md

chore(commands): typo

---

guide/interactions/context-menus.md

Currently the Links lead to 404 pages. I updated the links to the right pages.

Fixing the redirects to the slash command pages

---

guide/additional-info/changes-in-v14.md

feat(v14-changes): mention discord-api-types in the list of re-exported modules

---

guide/creating-your-bot/command-handling.md

fix(command-handling): add import for Events

---

guide/miscellaneous/cache-customization.md

the use of the sweeper is not documented enough, so I made an example of how the filter works in the sweeper.

Add more example for sweeper element.

---

code-samples/creating-your-bot/command-deployment/deploy-commands.js
guide/creating-your-bot/command-deployment.md

Fixes #1362. Credit to @LeCarbonator for the correct code

Use path module for reading commands folder

---

guide/creating-your-bot/command-handling.md

At this point there should be 3 command files in the commands folder and I just added the ones that were missing.

Added missing command file names

---

guide/creating-your-bot/command-handling.md

Highlights line 3 in a code section.
Going through this guide without importing Collection will result in the error "'Collection' is not defined."

+ Line of code was edited between articles

---

CONTRIBUTING.md
guide/.vuepress/components/DocsLink.vue
guide/additional-info/changes-in-v14.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/slash-commands.md
guide/interactions/context-menus.md
guide/interactions/select-menus.md
guide/popular-topics/reactions.md
guide/popular-topics/webhooks.md
guide/slash-commands/advanced-creation.md
guide/slash-commands/autocomplete.md
guide/slash-commands/permissions.md

Links the subpackages over to the new site.

feat(*): New site subpackages

---

guide/.vuepress/constants.ts
guide/additional-info/changes-in-v14.md

feat(*): Update guide to 14.9.0

---

guide/.vuepress/styles/mixins/scrollbar.scss

Fixes an issue where the scrollbar doesn't repaint to match theme on certain browsers until hovered over.

Fix for theme scrollbar

---

guide/slash-commands/advanced-creation.md

ChannelType is not defined which results to error

fix(advanced-creation): define `ChannelType` in example 

---

guide/popular-topics/threads.md

It has outdated information toast.

Archived Threads can be Locked.

---

guide/.vuepress/constants.ts
guide/additional-info/changes-in-v14.md
guide/popular-topics/permissions-extended.md

Updates the guide to 14.10.0.
Feel free to make a pull request to this branch or note changes in the comments.

feat(*): Update guide to 14.10.0

---

guide/message-components/interactions.md

fix(interactions): Fix awaiting components response methods

---

guide/interactions/modals.md

fix(modals): fix dead context reading link

---

guide/slash-commands/autocomplete.md

Change "Used to applying filtering" to "Used to apply filtering"

fix(autocomplete): "applying" typo

---

guide/interactions/modals.md

fix(modals): update allowed components in modal action row builders

---

guide/popular-topics/permissions.md

fix(popular-topics): typo in terminology

---

guide/creating-your-bot/README.md
guide/creating-your-bot/command-handling.md

These links no longer work. I believe the new links are correct.

fix: Update broken links

---

code-samples/creating-your-bot/event-handling/commands/utility/ping.js
code-samples/creating-your-bot/event-handling/commands/utility/server.js
code-samples/creating-your-bot/event-handling/commands/utility/user.js
code-samples/creating-your-bot/event-handling/config.json
code-samples/creating-your-bot/event-handling/events/interactionCreate.js
guide/creating-your-bot/event-handling.md

Following the guide from the beginning, there are some changes that need to be made to this page.
- The `Events.InteractionCreate` code wasn't up-to-date.
- Code samples were not 1:1 with the implementation in prior sections. This may cause confusion.
- This page interacts with `Events.InteractionCreate`, so I decided to dump the commands folder in the code sample.

fix(event-handling): Cleanup page

---

guide/message-components/select-menus.md

The first code excerpt on this page needed an extra line of highlighting.

fix(select-menus): string select menu highlight lines

---

guide/creating-your-bot/slash-commands.md

The wording there can be pretty confusing, so this clarifies things to avoid that

fix(slash-commands): clarify subfolder creation to avoid confusion

---

guide/sequelize/README.md

Text block under "syncing the model" highlighted wrong line (previously highlighted line was not new code and new highlighted line is correct)

fix(sequelize): Highlight correct code change in syncing

---

guide/popular-topics/faq.md
guide/popular-topics/formatters.md
guide/popular-topics/threads.md

refactor(popular-topics): prefer enums usage

---

guide/additional-info/changes-in-v14.md
guide/preparations/README.md

Update the required Node version from v16.11.0 to v18 (Discord.JS v14.16.0 minimum).

chore: Update required Node version texts

---

guide/popular-topics/formatters.md

Released on [formatters v0.5.0](https://github.com/discordjs/discord.js/releases/tag/%40discordjs%2Fformatters%400.5.0).

feat(popular-topics): add subtext formatter

---

code-samples/additional-features/reloading-commands/commands/utility/reload.js

Remove deleting commands from collection to match with what is on the guide.
Also related to this issue:- #1548

fix: remove deleting commands from collection

---

guide/popular-topics/faq.md

Updates how to retrieve the ping in the FAQ.

refactor(faq): Update ping section

---

code-samples/additional-features/cooldowns/index.js
code-samples/additional-features/reloading-commands/index.js
code-samples/creating-your-bot/command-deployment/index.js
code-samples/creating-your-bot/command-handling/index.js
code-samples/creating-your-bot/event-handling/events/interactionCreate.js
guide/additional-features/cooldowns.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/event-handling.md
guide/popular-topics/collectors.md
guide/slash-commands/response-methods.md

Replaced `ephemeral: true` with `flags: MessageFlags.Ephemeral` except for `InteractionDeferReplyOptions` which will happen in the next v14 release.

refactor: Use `MessageFlags.Ephemeral`

---

guide/sequelize/README.md

the "storage" line was displaying inline with the previous "logging" line.

fix(sequelize): new line in list

---

code-samples/keyv/index.js
guide/keyv/README.md

keyv no longer supports default imports

fix: Update keyv imports
