guide/assets/css/main.css

Fix an issue on Firefox where the last sidebar menu link was basically unclickable. Also lowered the amount of padding-top the sidebar had, since it looked kinda weird.

Fix unclickable last menu link issue

---

code_samples/.eslintrc.json
guide/assets/js/.eslintrc.json
guide/preparations/setting-up-a-linter.md

Provided a "base" ESLint file so that it doesn't seem like our file is the "correct" file. However, I left our file there (and adjusted one rule) in the case that the person reading doesn't want to create their own from scratch and would rather use someone else's to get started quickly (or for whatever other reason).

Adjust the ESLint page to make our config file "optional"

---

guide/additional-info/es6-syntax.md

Not sure how I missed this one. Probably not a good idea to use them and then have an example down below use the ES5 version when referencing the original. 😅

Adjust ES6 page to not use template literals before they're explained

---

guide/creating-your-bot/common-questions.md

Somehow it was using "<nickname>" for the `.setAvatar()` example.

Fix type in FAQ example

---

guide/command-handling/README.md
guide/command-handling/adding-features.md
guide/command-handling/dynamic-commands.md
guide/creating-your-bot/adding-more-commands.md
guide/creating-your-bot/commands-with-user-input.md
guide/creating-your-bot/configuration-files.md
guide/sharding/additional-information.md

Quite a few pages assume you're using code from the previous page, which may not always be true - some people might be visiting the link directly and may become confused because of that. This small message should at least clear that up.

Add an info message to pages that need them

---

code_samples/command-handling/adding-features/index.js
code_samples/command-handling/dynamic-commands/index.js
code_samples/command-handling/file-setup/index.js
code_samples/creating-your-bot/commands-with-user-input/index.js
code_samples/sequelize/currency/app.js
guide/command-handling/adding-features.md
guide/command-handling/dynamic-commands.md
guide/creating-your-bot/commands-with-user-input.md
guide/sequelize/currency.md

This does not make a difference in the majority of situations (as far as I'm concerned), if we ever provide a page for an eval command, this would break in certain situation, and would display some ugly output in many others.
```js
// this works
items.filter(item => {
return item.hasOwnProperty('active');
});
// this does not; returns `SyntaxError: Unexpected end of input`
items.filter(item => {
// some comment
return item.hasOwnProperty('active');
});
```
Even though splitting by `\s+` is better in other situations, splitting by just spaces seems better for Discord bots.

Split args by space and not \s

---

code_samples/sequelize/currency/dbInit.js
guide/sequelize/currency.md

As is, the `dbInit.js` script in the currency guide would not close on its own, due to the database connection staying open, and thus, the Node process staying open. I added a `sequelize.close()` line after all the syncing is done to remedy this.
In addition, I realized that you'd have to edit (and possibly unedit) the file each time you wanted to force sync the tables, which can get annoying if you edit your models a lot. I thought it'd be nice add a small bit of code to allow the user to execute `node dbInit.js --force` or `node dbInit.js -f` and have their DB forcefully sync without having to edit the source too often.
I've also reworded a bit of the relevant section, and adjusted some paragraphs in order to reflect these changes.

Reword currency DB init section, add --force arg, close connection after syncing

---

guide/additional-info/es6-syntax.md

* Fixed an ES5 example not actually being written in ES5 (along with missing a semicolon).
* Fixed a grammar error.
* Added a small example of destructuring with variable renaming.
* Move the template literals section above the arrow functions section, because the arrow function examples use template literals in the examples, so it doesn't make much sense to display that before they're explained.

ES5 example not actually in ES5

---

code_samples/additional-info/reactions/raw-event.js
guide/additional-info/reactions.md

I found out that a custom emoji isn't just mapped by it's ID, but by it's name:ID. The code can be shortened, but for clarity's sake I used an if statement so the reader knows what's going on.

Fix Reactions on old messages

---

guide/additional-info/miscellaneous-examples.md

You can replace `.send({embed: exampleEmbed})` with `.send({embed})` if the RichEmbed object is named "embed"

Added an additional note

---

guide/assets/css/dark.css

To prevent [this](https://i.imgur.com/jpMiZFr.png) from becoming [this](https://i.imgur.com/qyQdFQw.png).

Fix active sidebar link color from cascading down

---

guide/popular-topics/common-questions.md

With v11.3 being released recently, this section needed updating + an addition.
Also moved the notes into `<p class="tip">` tags and added a `<p class="warning">` tag with a note about `ClientUser#setActivity` only being available in v11.3, as well as `ClientUser#setGame`'s deprecation.

Update .setGame() example to .setActivity()

---

guide/assets/css/main.css

Instead of disabling all fade animations, this PR adds a smooth fade animation when toggling, as suggested by @Drahcirius in #66.

Add a smooth fade feature for theme toggling

---

guide/assets/css/main.css

Didn't notice till after #67 was merged, but it seems that some elements transition faster than others for some reason. This normalizes that.

More fade transition smoothness

---

TODO.md
guide/popular-topics/common-questions.md

2 simple examples that are asked almost daily in the support channels, as well as some `<p class="tip">` tags to accompany them with relevant, useful info. Also updated the reaction adding example, since you can just directly insert an emoji ID if you have that, instead of using `client.emojis.get('<id>')`.

Add bot restart and user tagging examples

---

guide/preparations/setting-up-a-linter.md

Previously provided https://atom.io/packages/eslint unsupported.   
`apm install eslint` fails with "No Available version compatible with the installed Atom version"  
[Issue](https://github.com/iancmyers/atom-eslint/issues) as of May 2016, Repo seems abandoned
Replaces relevant link in "setting up a linter" with  
https://atom.io/packages/linter (required)   
https://atom.io/packages/linter-eslint   
Adds reminder in tip that Atom now requires both packages to work

Update ESLint plugin for Atom with working alternative

---

guide/popular-topics/miscellaneous-examples.md

I saw some people talking about having trouble with the music bot example, and tried it out for myself on a fresh install.  I ran into a few issues when following the exact words of the tutorial, and tried to clear up the 2 errors that will probably pop up if someone's just copy-pasting the code and hasn't worked with discord.js before.  
The other thing I've seen firsthand from my own experience, as well as in conversations I lurked through in the discord server, is that this does not work in the Ubuntu subsystem for Windows 10. I'd like to put a clearer reason / explanation for why this doesn't work, but I don't have one.  I just know that playing audio this way even with a totally clean environment in the Ubuntu subsystem and following all the steps perfectly does not work.
Oh, and …

fixing a typo and explaining possible errors in the music bot example

---

code-samples/sharding/extended/bot.js
guide/sharding/extended.md

fixes #118 where the guide improperly assumes that the resulting emoji's guild is the same on as the current shard is.

fix: sharding not obtaining guild correctly

---

guide/popular-topics/permissions.md

- The section "Converting permission numbers" does currently not show how to use numbers for the constructor, which can be confusing. 
- `remove()` and `add()` in "Manipulating permissions" uses different values, which has already lead to confusion regarding if remove only takes numbers and add only takes flags.
It is described above, but for a clear visual representation and consistency i switched both over to flags here.

Permissions

---

guide/popular-topics/permissions-extended.md

Error occurs when trying to modify or assign a role, higher than or equal to the bots highest role

Permissions: include role assignment to "missing permissions"

---

guide/commando/README.md
guide/improving-dev-environment/pm2.md
guide/preparations/setting-up-a-linter.md

In a guide such as this, it's best to avoid using abbreviated commands whenever possible, since it's likely to be used by people who are new to the ecosystem or currently learning it. This PR just replaces the NPM install commands to use the non-abbreviated commands/params.

Avoid using abbreviated NPM commands

---

code-samples/additional-info/rest-api/index.js
code-samples/command-handling/adding-features/index.js
code-samples/command-handling/dynamic-commands/index.js
code-samples/command-handling/file-setup/index.js
code-samples/commando/getting-started/index.js
code-samples/creating-your-bot/adding-more-commands/index.js
code-samples/creating-your-bot/commands-with-user-input/index.js
code-samples/creating-your-bot/configuration-files/index.js
code-samples/creating-your-bot/up-and-running/index.js
code-samples/popular-topics/canvas/index.js
code-samples/popular-topics/permissions/index.js
code-samples/popular-topics/reactions/awaiting-reactions.js
code-samples/popular-topics/reactions/basic-reacting.js
code-samples/popular-topics/reactions/raw-event.js
guide/additional-info/async-await.md
guide/additional-info/es6-syntax.md
guide/additional-info/rest-api.md
guide/command-handling/README.md
guide/commando/README.md
guide/creating-your-bot/README.md
guide/popular-topics/canvas.md
guide/popular-topics/reactions.md

There were some recent issues that were brought up in the main discord.js repo about how ready event fires more than once. If people that follow the guide begin to use `.once()` for ready, then it could prevent issues like that in the future.

refactor: change all instances of .on('ready') to .once('ready')

---

guide/popular-topics/embeds.md

- Masked links in embeds allow an optional hovertext, people have seen it used on bots and webhooks for spoilers, so i figured we should probably include it here
- Embeds can only have one description, adapt wording

embeds: add hover text and clarify wording

---

guide/popular-topics/embeds.md

There was a typo in the Resending Embeds section. I took the opportunity to reword it slightly for clarity.

reword Resending Embeds section

---

code-samples/additional-info/rest-api/index.js
guide/additional-info/rest-api.md

As mentioned on the [snekfetch](https://www.npmjs.com/package/snekfetch) npm package, it has been deprecated and suggests to use node-fetch instead.
I have updated the rest-api article to use node-fetch instead of snekfetch.

Updating rest-api page to use Node-fetch instead of snekfetch

---

guide/creating-your-bot/commands-with-user-input.md

Since no one should actually have `client.on('message')` in their code I thought I'd just change it to ``client.on('message', ...)` so it's a bit more clear.

Small style fix for `client.on('message')`

---

guide/popular-topics/permissions-extended.md

The added cause was found on the discord server during support and not a thing we previously thought about.
Somehow the prefixing of a decimal with the hex indicator `0x` causes the API to reject the patch request for the overwrite update.  
Note: I'm not too familiar with the internal workings at this point and can just assume that the bots permissions are checked against the invalid permission number resulting in a rejected request. Since invalid permission values are usually accepted and used as-is and as applicable I'm not entirely sure of the underlying circumstances causing an error instead.

Update Permissions: Add missing permissions cause

---

guide/popular-topics/canvas.md

The link to the Canvas API (on MDN) is in a different language that does not match the default language of the guide, English.
The link directs the user to MDN's website under this language: https://developer.mozilla.org/kab/docs/Web/API/Canvas_API

Changed MDN link.

---

guide/popular-topics/embeds.md

One of the examples for raw embed data and how to edit it based on conditions uses the wrong format for color, this PR fixes this mishap.
Thanks @holroy for pointing it out

fix: color type in embed example

---

guide/popular-topics/miscellaneous-examples.md

Hello, 
Since I am not the biggest fan of Regex I never got to make a "prefix mention" myself, so after a quick Google search I stumbled upon the Discord Guide example and started using it. After a while, I was testing something inside of my Command Handler and changed the prefix of the bot to `r!`, in which, the given example on the Guide `r` gets escaped, completely breaking usage and forcing you to mention the bot. The escapes are obviously there so characters like `?` don't break it. After discussing with Space in the other-js-questions channel he recommended me to use the [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp) package.
So that is pretty much what this PR fixes, though I am unsure how to word a tip specifying what the used package does & …

Fix the Mention prefix example

---

code-samples/oauth/simple-oauth-webserver/index.html
code-samples/oauth/simple-oauth-webserver/index.js
guide/oauth2/README.md

There was a change in the fragment Discord provides when redirecting the user back to the redirect url so the regular expression did not work anymore.
Changed it to use URLSearchParams which was originally brought up in the past but didn't work because Discord wouldn't encode/decode certain things in the fragment leading to problems but now they do.
Also fixed a quote and added a tiny bit to the example for consistency i.e. getting user info from both client side and server side code.

Update OAuth2 Page

---

guide/popular-topics/reactions.md

Saying you "**didn't** react with neither this nor that" is a double negative. (Double negatives are grammatically frowned upon in the English language). You can refer to [this page](https://www.grammar-monster.com/lessons/either_or_neither_nor_double_negative.htm) for more information. (Read the "Quick Answer").

Double negative [didn't...neither...nor]

---

CONTRIBUTING.md
guide/.vuepress/branches.js
guide/.vuepress/components/Branch.vue
guide/.vuepress/components/BranchSelector.vue
guide/.vuepress/config.js
guide/.vuepress/eventBus.js
package.json
yarn.lock

This PR adds a `<branch>` component to the guide so that we can use it to conditionally render content on pages depending on the version the user selects from the dropdown menu shown above. This will allow us to easily account for both v11 and v12 syntax on the same page the rest of the relevant content is.
Examples:
```vue
Here's some conditional content that'll display depending on your choice from the site settings, in the dropdown menu from the cog icon above.
<branch version="11.x">v11.x content</branch>
<branch version="11.4">v11.4 content</branch>
<branch version="11.5">v11.5 (stable) content</branch>
<branch version="12.x">v12.x (master) content</branch>
```
And of course, you can see a live demo of this here: https://yuu-version-selector.netlify.com/version-selector.html
Finally …

Add branch version selector dropdown to user settings

---

guide/popular-topics/reactions.md

We relatively regularly had and still have people on the support server interpreting this approach as if it should react in order, although it clearly states that it does not.
I can see however, where the confusion is coming from. The guide part is called "reacting in order" and deals with that topic, so the removed snippet really does not belong here.
If you are in favor of keeping it, maybe as misc. code sample please let me know, although i'm not too sure in which context we'd fit it in there.
**Edit:** Keeping it under its own subheading instead of removing, as it still is useful information on how to deal with parallel promises at once.

Move Promise.all approach to its own subheading

---

guide/popular-topics/reactions.md

Since `max` is 1, an unfulfilled promise will always yield 0 reactions.

Fix code snippet for Awaiting reactions

---

guide/.vuepress/config.js

Adding a link to the official discord.js.org API documentation to the header of this guide.
Addressing [Issue 239](https://github.com/discordjs/guide/issues/239). When I was first researching how to create a discord bot, I was digging through Discord's official API and google searching for any javascript implementations. If you google how to create a discord bot, you end up being brought into the discordjs.guide site much more often (better SEO?).  The discoverability of the package's API is hard to find from that site and it took me a bit more googling to find the actual documentation. While there are links to the site from different pages in discordjs.guide, a top level link for more developers that are familiar with working with APIs would be helpful.
tl;dr; unless you know what to …

Create a header link to API documentation

---

guide/preparations/setting-up-a-linter.md

`"ecmaVersion": 2017` is from a while ago, and while not everyone will use newest features from ES9 or ES10, some may experience problems with ESLint returning parse errors from using for example rest operators in objects, as mentioned [in issue on official ESLint repository](https://github.com/eslint/eslint/issues/10307#issuecomment-391688204)
On the other side, from guide itself - `Alternatively, if you don't want to go through everything one-by-one on your own, you can use the ESLint file we use for this guide.`
Guide's config for eslint extends `sora/vue`, which has `ecmaVersion` set to `2019`

Use newer ecmaVersion in suggested ESLint configs

---

guide/miscellaneous/parsing-mention-arguments.md

Added null check if parameter supplied to `getUserFromMention` function in version with RegEx was indeed a mention.
Resolves #251

Add null check for getUserFromMention function

---

guide/oauth2/README.md

In the docs, a URL is missing a colon ( : ) after the scheme (https)

Add colon to HTTPS in Oauth2 readme

---

guide/popular-topics/miscellaneous-examples.md

[Example for command handler](https://discordjs.guide/command-handling/#command-handling) in the guide uses `.toLowerCase()` to get command. It's kind of missing in example for handling mention prefix.

Use .toLowerCase() in mention prefix example

---

guide/popular-topics/common-questions.md

Adding an example for fetching (counting) all online members in a guild as well as a way to monitor role addition and removal in the guildMemberAdd event.
Prompted by the ToDo section(s) by Souji (so blame him if it's unwanted).

Adding two examples

---

guide/sequelize/README.md

Mostly making the text consistent by removing instances of `we` and `us` in favor of a neutral or `you` speech.
Remove contractions for a slightly more formal speech; though that may be an arguable change.
I probably am missing some stuff so feel free to mention it.
There is also the sentence `SQlite will be used as the first storage engine, other database will be expanded upon later.`, which as far as I can tell is incorrect since the guide does not really expand on further DBs, so I'm not sure if this should stay or not.

Slight rework of the grammar/text in the sequelize guide

---

guide/.vuepress/branches.js
guide/.vuepress/components/BranchSelector.vue
guide/.vuepress/config.js
guide/.vuepress/styles/index.styl

This will allow people to link directly to the guide and set the user's version via a query string, e.g. `https://discordjs.guide/?v=12`, `https://discordjs.guide/?version=12`, `https://discordjs.guide/?v=stable` (11.x for now),  and `https://discordjs.guide/?v=master` (12.x for now).
Also moved the UI to the left of the cog icon, outside of the user settings menu, so that it's easy to tell which branch content you're currently viewing. To keep it mobile-friendly, the site name text gets changed to the guide book icon on mobile devices.
Desktop screenshot:
Mobile screenshot:
Resolves #273

Improve branch selector UI/UX

---

code-samples/creating-your-bot/configuration-files/index.js

Reverts discordjs/guide#278
Should not have been merged, the code is progressing as expected, and the changes made with this PR are only applied after the next guide section, where it's also applied in the code samples.
I overlooked this.

Revert "Enhance `configuration-files` example to utilize the configurized prefix."

---

guide/preparations/README.md

Under the "using command prompt" section, a branch-specific field is needed since node requirements are different between v11.x and v12.x.

Node version corrected with inline branch

---

.github/ISSUE_TEMPLATE/branching-content.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/typo_fix.md

This PR proposes some issue templates for use on the guide, filing as PR to allow feedback/requests for additions/changes/wording improvements etc.
This removes the need for manual tagging for the most common issue types.
Where applicable uses the standard GitHub suggestion, possibly adapted to fit the context of the guide better.
* Added the `branching` tag to mark requests and PRs that deal with branching content (e.g. needs v12 implementation) which will automatically be assigned if the corresponding issue template is selected.

Add issue templates

---

guide/additional-info/changes-in-v12.md

Clearing all reactions is achieved with `removeAll()` not the inherited map method. 
(spotted by LostSorrow#1237)

Fix ReactionStore method

---

guide/preparations/README.md

Fix malformed branch tag

---

guide/popular-topics/embeds.md

* local images -> attaching images
* tip about avoiding re-attaching a file over and over
* resending -> resending and editing
* turn part about received embed structures into a warning
* add section about editing embedded message content
We keep linking "resending embeds" and need to add that editing works mostly the same or get the response that the user being helped does not really want to resend an embed. This PR changes this part of the guide to be more semantically correct and address this duality.
I also took the liberty to change some elements for increased verbosity.

feat: embed guide rewording + embed editing

---

code-samples/command-handling/adding-features/12/commands/avatar.js
code-samples/command-handling/dynamic-commands/12/commands/avatar.js
code-samples/command-handling/file-setup/12/commands/avatar.js
code-samples/command-handling/file-setup/12/index.js
code-samples/creating-your-bot/commands-with-user-input/12/index.js
code-samples/miscellaneous/parsing-mention-arguments/12/index.js
guide/additional-info/changes-in-v12.md
guide/creating-your-bot/commands-with-user-input.md

discord.js introduced a dynamic option for image URLs, which should be used to receive expected results (animated images being displayed as gif) throughout the v12 guide and in the changes section.
* use dynamic URLSs throughout the guide
* use dynamic URLs in code samples
* fix non-method usage of URL in code samples
* explain dynamic in v12-changes

feat(v12): dynamic urls

---

guide/popular-topics/reactions.md

This PR updates the reactions page for master, [030d263](https://github.com/discordjs/discord.js/commit/030d263a9e018a766c5f399624fe4f8ec2b7349c) introduced support for the new endpoint which allows you to remove a reaction completely with one call. This PR simply updates the master version to use that.

Change reactions page to use MessageReaction#remove

---

guide/popular-topics/canvas.md

Canvas guide had a typo when referencing the `MessageAttachment` class, which should be `Attachment` for the stable branch of discord.js.

typo: change MessageAttachment to Attachment

---

code-samples/additional-info/rest-api/12/index.js
guide/additional-info/changes-in-v12.md
guide/additional-info/rest-api.md
guide/popular-topics/embeds.md
guide/popular-topics/errors.md

This PR changes `addField` to `addFields` for v12 code in embed and rest-api guides, as well as updates field related errors in common discord.js errors, and finally adds the fact of change to changes-in-v12.
Supersedes #331

Change addField to addFields for v12

---

guide/additional-info/async-await.md

this PR fixes a typo in the additional-info/async-await section of the guide

typo: additional-info/async-await

---

guide/additional-info/changes-in-v12.md

Notes that `client.destroy()` no longer returns a promise in v12.  Also resolves #345 by adding changes to `presenceUpdate` event.

Add missing updates to Client information

---

guide/.vuepress/branches.js

Changed the default Discord.js version of the guide to v12 because it is now stable

Change default Discord.js version of guide to v12

---

guide/popular-topics/partials.md

This PR fixes the error in the partials.md file : `Discord` was defined but only the `Client` class was used

Fix error in partials guide

---

README.md

Before the links to various pages in the guide were for example `https://discordjs.guide/#/preparations/` which would take you to the homepage, so this commit fixes them to remove the `/#`: `https://discordjs.guide/preparations/`.

docs(readme): fix links to guide

---

guide/popular-topics/reactions.md

Whenever you iterate over a Collection with ``for...of`` loop, it has two parameters, a key and a value. This pr fixes those parts where ``for (const reaction of userReactions)`` is used, because the first parameter of the collection represents the `Snowflake`, and the second represents the `Object`. This has been fixed by the use of destructured array here.

fix: for..of iteration in reactions guide

---

code-samples/command-handling/adding-features/11/commands/reload.js
code-samples/command-handling/adding-features/12/commands/reload.js
guide/command-handling/adding-features.md

This PR fixes #358 by not using passed argument as command's file name, but instead using name property that command file exports.

Fix reloading via alias

---

guide/voice/the-basics.md

This PR removes the `passes` option from the `VoiceConnection#play` example of the `Voice` guide in the `Playing audio` section.
This option was removed with the release of 12.0.0 and additionally Discord does not want to receive multiple streams of the same voice packets at all.

fix(Voice): remove passes option from example

---

code-samples/popular-topics/permissions/12/index.js
guide/popular-topics/permissions.md

Fix the V12 example for overwritePermissions() in the permissions guide which showed  ~~V11.X~~ master methodology.
One could argue demonstrating the `reason` option as well, but I don't personally see that as important here.

fix example(s) of overwritePermissions()

---

code-samples/command-handling/adding-features/11/commands/reload.js
code-samples/command-handling/adding-features/12/commands/reload.js
guide/command-handling/adding-features.md

After looking more into the inconsistency raised by #377 the success message semantically fits better into the try block instead of returning on catch. To facilitate this change I also mentioned the location explicitly in the guide article
* mention the location explicitly in the guide
* adapt code samples
* Closes #377

fix: move success message into try block

---

guide/additional-info/changes-in-v12.md

This PR adds information to the v11 to v12 update guide about `disabledEvents` being removed in favor of specifying intents in `clientOptions`.

Add information about intents

---

guide/popular-topics/intents.md

Fixes a typo, The events included in the **intents** not events.

chore: fix typo in the intents guide

---

guide/popular-topics/collectors.md

Add version branches to the ReactionCollector sample code.
Add a usage example for the User argument plus fallback code for v11.
This PR fixes a misleading code example for v12:
```js
const collector = message.createReactionCollector(filter, { time: 15000 });
collector.on('collect', (reaction, reactionCollector) => {
console.log(`Collected ${reaction.emoji.name}`);
});
```
In v12, the second argument is a `User` and not a `ReactionCollector`, and in both versions of the example the second argument isn't actually used.
As per [discussion in Discord](https://discordapp.com/channels/222078108977594368/682245563193884710/704015971610001468), this PR adds an example for using the User argument, and equivalent v11 code …

fix: arguments for ReactionCollector collect handler

---

guide/sharding/extended.md

I switched around the parameters used when instantiating the `GuildEmoji` constructor which is used in the [Sharding](https://discordjs.guide/sharding/extended.html#using-functions-continued) section of the Discord.js Guide. In accordance with the [documentation](https://discord.js.org/#/docs/main/stable/class/GuildEmoji), this is the correct order of parameters for the constructor:
```js
new Discord.GuildEmoji(client, data, guild);
```
I realized when using the original code in the guide, I was getting incorrect information when logging the `GuildEmoji` object in the console: https://i.imgur.com/xTQrvIz.png

Switch parameters for usage of GuildEmoji constructor

---

guide/sharding/additional-information.md

TL;DR
- Moved `--trace-warnings` from `shardArgs` to `execArgv`
- Reworded note about `process.argv` suggesting it's not needed to access it if passing arguments
- Reworded note about `process.argv` about only containing `shardArgs`
---
The current example of `ShardingManger#shardArgs`  in the guide uses `--trace-warnings` as an argument for the script file rather than the executable (i.e. node).
Doing this is rather confusing, or perhaps misleading, as this is actually a node command line option. ([docs](https://nodejs.org/api/cli.html#cli_trace_warnings))
While it certainly _is_ possible to use this as a custom argument for your script, the guide should not do this to avoid confusing the reader.
I therefore moved …

refactor(Sharding): move --trace-warnings to execArgv in additional-information

---

guide/command-handling/adding-features.md
guide/commando/permissions.md
guide/creating-your-bot/adding-more-commands.md
guide/miscellaneous/parsing-mention-arguments.md
guide/popular-topics/collectors.md
guide/popular-topics/embeds.md
guide/popular-topics/errors.md
guide/popular-topics/permissions.md
guide/popular-topics/reactions.md
guide/popular-topics/webhooks.md
guide/sharding/README.md
guide/sharding/additional-information.md

There is still a bunch of links pointing to the master branch of the documentation (partially outdated) back from when v12 was in development.
This PR replaces them with the respective (now) stable counterparts and adapts the surrounding sentence where necessary

fix: port documentation links to stable

---

guide/additional-info/changes-in-v12.md

I removed escape characters that shouldn't be showing in the Markdown render at [voiceBroadcast#play***](https://discordjs.guide/additional-info/changes-in-v12.html#voicebroadcast-play).
> All `.play\*\*\*()` methods have been removed and transformed into a single .play() method.

Removed escape characters showing in Markdown

---

guide/.vuepress/branches.js
guide/command-handling/README.md
guide/command-handling/adding-features.md
guide/commando/permissions.md
guide/creating-your-bot/adding-more-commands.md
guide/miscellaneous/parsing-mention-arguments.md
guide/popular-topics/collectors.md
guide/popular-topics/embeds.md
guide/popular-topics/permissions.md
guide/popular-topics/reactions.md
guide/popular-topics/webhooks.md
guide/sharding/README.md
guide/sharding/additional-information.md

This updates the version selector to display 11.6 instead of 11.5 for the `11.x` branch.
Also, rewrites all 11.x specific doc links to `v11` branch of the docs (was `11.5.1`).
Also fixes a link to Collection in `reactions.md` by adding appropriate branching.
[Discussed](https://discordapp.com/channels/222078108977594368/682245563193884710/706862128597958727) in Discord.

chore: change label to v11.6 + point docs to v11 branch

---

guide/popular-topics/partials.md

A nitpicky PR that changes "both" to "all of" because both is only used for two options.

Change "both" to "all of"

---

guide/additional-info/changes-in-v12.md

**Please describe the changes this PR makes and why it should be merged:** Guide improperly documented the change as `clientUser.guilds.create()` when it's supposed to be `client.guilds.create()`.

fix: Correct mistake on clientUser#createGuild change from v11 to v12.

---

guide/sharding/README.md

This PR has multiple improvements to the Sharding guide:
1. The guide stated that for 3600 guilds and 4 shards, they will be distributed as `[1000, 1000, 1000, 600]`. My best understanding of sharding is that every shard will have ~900 guilds. The guide was updated to reflect it.
2. A notice was added that ShardingManager can only run shards on the same machine (as processes / threads).
3. Some rewording (e.g. "I" -> "we") and clarifications
4. Small formatting fix: newline after `</branch>`
**Why is the PR submitted as a draft**
I never worked with sharding, so I would like confirmation that my understanding is correct. Also, perhaps there's a better place for the remark about scaling beyond processes on the same …

Tweaks to Sharding guide

---

guide/popular-topics/reactions.md

Fixes the incorrect name of the `GUILD_PRESENCES` intent added in https://github.com/discordjs/guide/commit/5e11b51c9cddd8b024bb89456dee25e3a6edb3bf

fix(reactions): fix presence intent name

---

guide/popular-topics/collectors.md

This PR replaces the ok-hand emoji with 👍.
Closes #427 
Closes #428

refactor: use thumbs up emoji in examples

---

guide/additional-info/changes-in-v12.md

This PR corrects the class names at the beginning of the v12-changes section from `Channel` to `TextChannel`
also fixes some missing capitalisation near `CategoryChannel#members`

fix(additional-info/changes-in-v12): correct class names

---

guide/sharding/README.md
guide/sharding/additional-information.md
guide/sharding/extended.md

Recent commit [d2a5acf](https://github.com/discordjs/guide/commit/d2a5acf1a9b1beb720970437edd089718b0ad8c9) added incorrect informations about [`Shard`](https://discord.js.org/#/docs/main/stable/class/Shard) being able to have multiple IDs.
`Shard`s are already shards, they have single ID. It's the `Client` that is able to have multiple shards with internal sharding, so it's [`Client.shards`](https://discord.js.org/#/docs/main/stable/class/ShardClientUtil) that is an array.

Partially revert recent commit fixing sharding guide

---

code-samples/additional-info/rest-api/11/index.js
code-samples/additional-info/rest-api/12/index.js
code-samples/command-handling/adding-features/11/index.js
code-samples/command-handling/adding-features/12/index.js
code-samples/command-handling/dynamic-commands/11/index.js
code-samples/command-handling/dynamic-commands/12/index.js
code-samples/command-handling/file-setup/11/index.js
code-samples/command-handling/file-setup/12/index.js
code-samples/creating-your-bot/commands-with-user-input/11/index.js
code-samples/creating-your-bot/commands-with-user-input/12/index.js
code-samples/keyv/index.js
code-samples/sequelize/tags/sequelize.js
code-samples/sharding/extended/11/bot.js
code-samples/sharding/extended/12/bot.js
code-samples/sharding/getting-started/11/bot.js
code-samples/sharding/getting-started/12/bot.js
guide/additional-info/rest-api.md
guide/command-handling/README.md
guide/command-handling/adding-features.md
guide/command-handling/dynamic-commands.md
guide/creating-your-bot/commands-with-user-input.md
guide/keyv/README.md
guide/sequelize/README.md
guide/sharding/README.md
guide/sharding/extended.md

This PR makes use of `trim()` after slicing the prefix when declaring `const args`. This should allow for using spaces between prefix and command without issues.
Additionally includes explanation in `guide/creating-your-bot/commands-with-user-input.md` for that, but it probably could be improved.
Closes #383 by superseding.

Use trim after slicing off the prefix

---

guide/additional-info/changes-in-v12.md

Accessing `VoiceConnection` changed from `.voiceConnection` to `.voice.connection`, but it was not listed in the updating guide.

Add missing new VoiceConnection accessing

---

code-samples/oauth/simple-oauth-webserver/index.js
guide/oauth2/README.md

In the guide you stated that you are using the npm [`form-data`](https://www.npmjs.com/package/form-data) module to convert the data to `application/x-www-form-urlencoded` as requested by [Discord](https://discord.com/developers/docs/topics/oauth2) and RFC 6749, however you used it actually which sends data as `multipart/form-data`.
It seems that discord accepts this format but it is different that what Discord recommends and what is stated in the guide. Adding `headers: { 'Content-Type': 'application/x-www-form-urlencoded' }` to the `fetch` call makes Discord flag it as invalid as the payload is in a different format.
https://medium.com/@rajajawahar77/content-type-x-www-form-urlencoded-form-data-and-json-e17c15926c69

replace 'multipart/form-data' with 'application/x-www-form-urlencoded'

---

guide/popular-topics/intents.md

I read your article about [gateway intents](https://discordjs.guide/popular-topics/intents.html) in detail and I noticed that the [discord support article](https://support.discord.com/hc/articles/360040720412) says something different conecerning privileged intent whitelisting:
> Please note that this is currently in a deprecation period and you will require a whitelisted bot in order to use privileged intents as of October 7, 2020. ~ https://discordjs.guide/popular-topics/intents.html
> After our deprecation period ends, if your bot is in over 100 servers, you cannot turn on Privileged Intents until you get whitelisted first. ~ https://support.discord.com/hc/articles/360040720412#what-if-im-already-in-100-guilds-1
So whitelisting is only required if a bot is in more than 100 guilds 😅 I …

Corrected misleading information

---

code-samples/command-handling/adding-features/11/commands/reload.js
code-samples/command-handling/adding-features/12/commands/reload.js
code-samples/popular-topics/reactions/12/uncached-messages.js
guide/command-handling/adding-features.md
guide/miscellaneous/useful-packages.md
guide/popular-topics/reactions.md

resolves #475 
This PR changes some code samples to use `console.error` over `console.log` to
1. make it less confusing for some people (as seen in #475?)
2. to log the errors to the `stderr` rather than `stdout`

fix: use console.error when logging errors

---

guide/additional-info/changes-in-v12.md

Fixes ‘Dynamic File type’ in the updating to v12 guide to be a heading level 3 (used to be level 2).

fix(v12-changes): fix ‘Dynamic File type’ heading

---

guide/popular-topics/permissions.md

Fixes a 404 caused by a typo in [popular-topics/Permissions>Permissions after overwrites](https://discordjs.guide/popular-topics/permissions.html?v=12#permissions-after-overwrites).

fix(permissions): 404 caused by typo in docs URL

---

CODE_OF_CONDUCT.md
guide/README.md

This PR add a Netlify badge and a code of conduct file in order to meet the criteria for [Netlify's Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/). An open source plan has the same benefits as their pro plan, which will benefit the guide in a few ways.

feat: Add Netlify badge to intro page

---

code-samples/miscellaneous/parsing-mention-arguments/11/index.js
code-samples/miscellaneous/parsing-mention-arguments/12/index.js
guide/miscellaneous/parsing-mention-arguments.md

This guide page originally opened with an example of a ban command which can go haywire due to
wrong usage of `message.mentions` and showed a method for fixing it.
However the example `avatar` command does not make good use of manually parsing mentions, so a second
example has been added to clearly show the advantage of manually parsing mentions in a ban command.

feat(parsing-mentions): add second command that showcases multiple mentions

---

guide/additional-info/changes-in-v12.md

In the guide, it states that client#shardResume has the parameters "replayed" and "shardID". These are in fact backward, as in the docs it states the parameters are "shardID" THEN "replayed". Tested this with my own bot to confirm that the order was incorrect for the guide instead of the docs.
Changes guide on v11 to v12 changes for client#shardResume to show correct parameter orders instead of backward. Making sure that errors are not given when users are updating from v11 to v12 and using this event.

Update v11 -> v12 changes for client#shardResume

---

guide/additional-info/changes-in-v12.md

There was an error with some grammar where there was a sentence that was falsely doubled-up, where;
`The The messages` has been corrected to `The messages`

Grammar Fix

---

guide/.vuepress/config.js

Currently, vuepress removes the charset and viewport meta tags.
This causes Firefox Mobile to display the page in desktop view.
This PR forces vuepress to add the tags again.
Currently:

fix: force viewport and charset meta tags

---

guide/command-handling/adding-features.md

The  example code in https://discordjs.guide/command-handling/adding-features.html#command-permissions gets the permissions of the bot itself rather than the command author. This patch fixes that.
The separate code-samples themselves already have this patch, it seems.

use permissions of command author rather than of the bot

---

guide/popular-topics/intents.md

⚠️ closes #570
When Discord stopped sending events for privileged intents and required action from developers in order to restore the full functionality of their bots the number of requests in various support channels has made it necessary to provide a straightforward manual on how to handle the situation.
In preparation for v13 (which will require websocket intents to be specified due to Discord.js using v8 of the Discord REST API and gateway) we should explain how users provide intents to the Client constructor.
This PR aims to do so. As always I'm grateful for reviews and improvement suggestions.

feat(Intents): replace Intents placeholder

---

guide/popular-topics/intents.md

I read the revised version of you on Gateway Intents and thought it was very good. I still have the suggestion to separate the effects of the individual privileged intents and format them as a list or table. Here are both options, currently the table is my choosen format in the PR.
> Table
> 
> ![Lightmode](https://i.imgur.com/7s8F8z7.png)
> 
> ![Darkmode](https://i.imgur.com/JBPyUzq.png)
> List
> 
> ![Lightmode](https://i.imgur.com/ReyFXqu.png)
> 
> ![Darkmode](https://i.imgur.com/pEQ6b8l.png)

Rework of missing privileged intents symptoms as table

---

code-samples/command-handling/adding-features/11/index.js
code-samples/command-handling/adding-features/12/index.js
guide/command-handling/adding-features.md

fixes: #615
This PR makes the `cooldowns` collection a property of `client`. Thus, making it possible to access the `cooldowns` in the `message.js` file later in the `event-handler` section. This change will somewhat reduce the hassle of adding back additional command-handling features after a reader has implemented the event-handler.

feat(command-handling): Make cooldowns a property of client

---

guide/popular-topics/intents.md

There was an unpaired backtick in the "Enabling Intents" part of the guide, and it broke that paragraph's formatting.

fix unpaired backtick in intents

---

code-samples/oauth/simple-oauth-webserver/config.json
code-samples/oauth/simple-oauth-webserver/index.html
code-samples/oauth/simple-oauth-webserver/index.js
guide/oauth2/README.md

This PR rewrites the OAuth page to use express instead of the native http module. A few touch-ups have been made as well, in terms of readability, comprehension, etc.
Closes #472.

refactor(oauth): Use express instead of native http module

---

guide/preparations/setting-up-a-linter.md

- Marks eslint as a dev dependency, as it's recommended on https://eslint.org/docs/user-guide/getting-started
- Mark caveats in global install mentioned on the same eslint getting started page.

Update eslint install instructions

---

guide/popular-topics/faq.md

It adds information about `ClientOptions#allowedMentions` /  `MessageOptions#allowedMentions` to the FAQ, thus answering a Frequently Asked Question.

feat: add allowedMentions to faq

---

guide/preparations/setting-up-a-bot-application.md

Repl.it has recently changed how it stores environment variables. This PR reflects that and links to the new page in the documentation.

Fix link to repl.it docs

---

guide/popular-topics/embeds.md

Since interactions use webhooks to send their messages, more and more users are discovering them and so, I think it's good to specify that the 6000 char limit applies to all characters from all embeds in a message, and not individually like the previous description could lead you to believe.

Specify that the 6000 char limit applies to all embeds in a message

---

guide/oauth2/README.md

`window.load` -> `window.onload`

---

guide/popular-topics/intents.md

- be more explicit about how to read discord developer docs to figure out intents
- reword to prefer applications instead of bot
- replace invite link with vanity
- remove explicit mention of #missing (not all that useful if you don't have a very specific use case)
- reorder sections to better fit required reading order
- closes #675

refactor(intents): more explicit on how to read ddev docs

---

guide/.vuepress/sidebar.ts
guide/interactions/registering-slash-commands.md
guide/interactions/replying-to-slash-commands.md
guide/interactions/slash-command-permissions.md

This PR adds an Interactions category to the side bar and adds a guide on how to reply to slash commands based on discordjs/discord.js#5448 .
I expect this to be held off for until the aforementioned PR is merged and the next major version of the lib is released.
I have paid utmost attention at everything outlined in `CONTRIBUTING.md`, and made sure to avoid grammatical and other errors, however as this is my first contribution I expect that some things will need to be adjusted/fixed/rewritten to fully satisfy the requirements, and I am happy to do so as the reviews come in.

feat: interactions and slash commands

---

guide/preparations/setting-up-a-linter.md

Update the Eslint rules to support the ES2021 since the guide and the docs use the optional chaining and the null coalescing operator and in the ES6 rule it gives a warn

Suggestion: Eslint Rules

---

.github/ISSUE_TEMPLATE/config.yml

This updates the invite link in the `config.yml` file to the new vanity URL. It allows users to use a more updated link and use a shorter version.

chore(.github): update invite link

---

guide/.vuepress/sidebar.ts

Except the 1st one, all of these result to a 404 because of the voice rewrite PR making way for a dedicated section for voice. It removes the outdated sidebar links.
(I realized this was committed directly to `v13-prep` on my end so I'll re-fork again when needed.)

fix(sidebar): remove outdated voice-related links

---

guide/interactions/registering-slash-commands.md
guide/interactions/replying-to-slash-commands.md

Two links in the slash commands pages lead to 404s due to bad URLs. This fixes the URLs to lead to the right pages.

fix(interactions): Fix broken links

---

guide/interactions/registering-slash-commands.md

Per discordjs/discord.js/pull/6204, "subcommand" and "subcommand group" should be preferred and should be consistent here in the guide! Although not quite sure why it was initially "sub-command-group".

fix(interactions): Use subcommand (group) casing

---

guide/popular-topics/collectors.md

This PR just fixes a typo in the `awaitMessageComponents` method which should be `awaitMessageComponent`

fix(collectors): typo in awaitMessageComponent

---

code-samples/command-handling/file-setup/13/commands/avatar.js
code-samples/command-handling/file-setup/13/commands/kick.js
code-samples/command-handling/file-setup/13/commands/options-info.js
code-samples/command-handling/file-setup/13/commands/prune.js
guide/interactions/registering-slash-commands.md
guide/interactions/replying-to-slash-commands.md

This PR updates the examples to use the commandinteractionresolver methods and adds the missing number option type.

fix(interactions): use cmd opt resolver & add missing option type

---

code-samples/popular-topics/webhooks/13/using-WebhookClient.js
guide/popular-topics/webhooks.md

Per [PR 6192](https://github.com/discordjs/discord.js/pull/6192) in the discord.js repo, webhook constructors now only accepts an object property, which in turn can contain either id + token or url. This doesn't update the message parts (see #740 for that), and I didn't place it there either because this has a different scope. The guide and samples are changed.

feat(Webhooks): use new webhook constructor syntax

---

guide/interactions/registering-slash-commands.md

Changes the advanced deployment code in the guide to use an async function, since TLA only works in es6 modules, and it would throw an error otherwise, and also for consistency with discordjs/discord.js#6250

fix: async function in advanced deployment example

---

guide/.vuepress/sidebar.ts
guide/.vuepress/theme/layouts/Layout.vue
guide/whats-new.md

This adds a "What's new" page for the release of discord.js v13. It lists a few site changes, the new pages, and the notable updated content.

feat: Add "What's new" page

---

guide/creating-your-bot/configuration-files.md

This fixes the code example in the guide for logging in a client with a token from a config file, to be consistent with the guide's code repo.

fix: change config token code example to match repo

---

guide/creating-your-bot/adding-more-commands.md
guide/creating-your-bot/configuration-files.md

In this context of the guide, prefixes are not used, needless to say, slash commands are the ones here.

fix: remove mentioning of prefix usage

---

guide/interactions/registering-slash-commands.md

Typo in the example. Should say "successfully".

fix: typo in "Advanced deployment" example

---

guide/voice/audio-player.md

This PR fixes the broken link on the voice page to audio resources, as previously it would lead to a 404 upon click.

fix: Patch broken link to Audio Resources page

---

guide/interactions/buttons.md
guide/interactions/replying-to-slash-commands.md
guide/interactions/select-menus.md

This PR renames all instances of `defer` to `deferReply` as per recent commit to djs

fix(Interactions): rename defer to deferReply

---

guide/voice/audio-player.md

it's literally just fixing the names of the variables used in the example, because the previous example used the wrong names

player.* and AudioPlayerStatus.* instead of connection.* and VoiceConnectionStatus.*

---

guide/additional-info/changes-in-v13.md

this changes the typo in `TextChanel` to `TextChannel`

fix: typo in TextChannel

---

guide/interactions/replying-to-slash-commands.md

The previous PR was merged quickly without reviews and one single instance of `defer()` managed to skip through, this is hereby corrected to `deferReply()`.

fix(Interactions): rename last remaining defer to deferReply

---

guide/additional-info/changes-in-v13.md

Adds `Channel#isVoice()` (https://github.com/discordjs/discord.js/pull/6297) to the additions section of v13 changes.

feat(v13-changes): Channel#isVoice() in v13 additions

---

guide/.vuepress/config.ts

I feel the Algolia API key should not be a part of the main code, pretty sure Algolia has a limit for the number of requests per month. I don't think Google Analytics Id should be a part of code either.
This would require the guide to add  Netlify environment variables for the Algolia API key as well as Google Analytics ID

fix: Implement environment variables in config file

---

guide/interactions/replying-to-slash-commands.md

Closes #754 and splits the parsing options section into regular option parsing and a detailed example on parsing subcommands and their options.

feat(Interactions): add subcommand parsing section

---

guide/interactions/slash-command-permissions.md

Chaning **GuildApplicationCommandManager#setPermissions** see [this](https://discord.js.org/#/docs/main/stable/class/GuildApplicationCommandManager)
to **ApplicationCommandPermissionsManager#set** see [this](https://discord.js.org/#/docs/main/stable/class/ApplicationCommandPermissionsManager)
Because **GuildApplicationCommandManager#setPermissions** is not a thing(anymore)
and its **ApplicationCommandPermissionsManager#set** that used on the example `await client.guilds.cache.get('123456789012345678')?.commands.permissions.set({ fullPermissions });`

Changing a method on the example 

---

code-samples/sequelize/currency/13/models/UserItems.js
guide/sequelize/currency.md

The default primary key (`id`) generated by Sequelize is of type `INTEGER`, and `item_id` here uses the `id` value of items in the currency shop.
Resolves #742

fix(sequelize): data type of `item_id`

---

guide/.vuepress/sidebar.ts
guide/popular-topics/builders.md

As discussed in the dev corner, this PR adds a page to the popular topics section showcasing the usage of the @discordjs/builders package.

feat(Builders): add builders page to popular-topics

---

guide/popular-topics/permissions-extended.md

This PR fixes a typo in the guide. "Discords" is incorrect, it should be "Discord's".

chore: Fix a typo (Discords => Discord's)

---

guide/interactions/registering-slash-commands.md

Without this change, the link uses the relative path and so keeps the /interactions meaning this is currently a 404.

fix: corrects link level to popular-topics

---

guide/popular-topics/permissions.md

Correctly uses the `.edit()` method of the PermissionOverwriteManager. See the docs [here](https://discord.js.org/#/docs/main/stable/class/PermissionOverwriteManager?scrollTo=edit).

fix(popular-topics): editing permission overwrites

---

guide/interactions/registering-slash-commands.md

As per the PR being merged in discordjs/discord.js#6354, this PR makes the same change to the guide, because as explained in that PR, it will stop people trying to install `discord-api-types/v9` in their terminal, and explicitly states to install `discord-api-types`

feat: Mention install discord-api-types in registering slash commands

---

guide/interactions/replying-to-slash-commands.md

This refactors the examples in the options parsing section to use the slash command builder for consistency across the pages.
Should be held off until https://github.com/discordjs/builders/pull/23 is merged and a release is published.

refactor(Interactions): use builders in options parsing

---

guide/preparations/adding-your-bot-to-servers.md

The template link provided by the guide uses a different template than the one provided by discord's OAuth2 app page, so I modified it to use the one provided by discord. I also updated the URL part by part of the parsing by adding the explanation of the authorization part and I completely rewrote the link building part so that it explains hot to do it with OAuth2 page.
I think this is an easier and more reliable way to generate the invite link

Fix: Update the invite link structure and explanation

---

guide/interactions/registering-slash-commands.md

This PR aims to add the definition of GUILD_ID and CLIENT_ID to registering slash commands.
Although these could just be hardcoded in the relevant place, the (faulty) half definitions suggested would present a more explicit "do thing here" to the users.
If it is scanned over and ignored, the error should (I would hope) be pretty obvious to anyone who encounters it.

Add explicit variable definitions for client and guild id

---

guide/popular-topics/audit-logs.md

The `guildBanAdd` event's parameters still used version 12's parameters!

fix: Update `guildBanAdd` parameters to version 13

---

guide/popular-topics/builders.md

Replaces the method `memberMention` with `memberNicknameMention`.

fix(popular-topics): `memberMention` with `memberNicknameMention`

---

code-samples/additional-info/rest-api/13/index.js
guide/additional-info/rest-api.md

See https://nodejs.org/api/querystring.html. The query-string module is considered legacy and therefore not recommended to use, even if it has not yet been deprecated. The `URLSearchParams` class can also achieve the same thing in this context and is tested to work (v16.6.x).

feat(rest-api): use native URLSearchParams class for Urban Dictionary sample

---

guide/interactions/registering-slash-commands.md

Removes extra space after an inline codeblock.
Before: if your application has the `applications.commands ` scope authorized.
After: if your application has the `application.commands` scope authorized.
See above, just a typo fix.

Typo: Removes extra space after codeblock

---

guide/popular-topics/faq.md

Without the `GUILD_VOICE_STATES` intent, the bot account joins the specified voice channel, but is stuck in the **Signalling** state, never advancing to the **Connecting** or **Ready** state. Without this connection, the bot player switches to Idle immediately after `play` is called since there are no connections to play audio to. Adding this intent warning will greatly help developers who may not otherwise know where their code went wrong (like I certainly did).

Update Playing music from YouTube section to require `GUILD_VOICE_STATES` intent

---

guide/whats-new.md

The `Command Handling` hyperlink redirects to the old path, leading to a 404 error code, This PR replaces the old link with the new one.

fix: replace broken link

---

guide/popular-topics/builders.md

Fix a typo in the [`popular-topics/builders`](https://discordjs.guide/popular-topics/builders.html) page
> foollowing -> following

fix: "foollowing" -> "following"

---

code-samples/additional-info/rest-api/13/index.js
guide/additional-info/rest-api.md
guide/creating-your-bot/README.md
guide/popular-topics/embeds.md
guide/popular-topics/faq.md

This PR includes the following changes:
- additional-info/rest-api
- deferring replies then replying to them in case of slow internet/servers
- fixed links not being correctly hyperlinked (clickable)
- creating-your-bot/
- renamed "TOKEN" environment variables to "DISCORD_TOKEN", which is what `Client.login()` defaults to. We are still keeping `client.login(process.env.DISCORD_TOKEN)` to be explicit. This change was not made for config variables
- popular-topics/embeds
- included embed title to the resolved mentions list
- popular-topics/faq
- included embed title to the resolved mentions list
- changed case ("Websocket" or "WebSocket" -> "websocket") when being used in the middle of a sentence
- dictionaries say …

refactor: code improvements, FAQ refactors, and more

---

guide/sequelize/README.md

* fix SQL query examples
* name VARCHAR(255) UNIQUE
I believe this would make this line equivalent to the Sequelize code since the "name" is not unique on the SQL example.

Fix for SQL example on Sequelize guide

---

guide/additional-info/changes-in-v13.md

As raised in [#guide-discussion](https://canary.discord.com/channels/222078108977594368/682245563193884710/893718836350709781) one of the thread events was missing from this list.

fix: missing thread event

---

guide/popular-topics/permissions-extended.md

With slash commands, a new cause for `Missing Access` has arrived. While this doesn't really fit into the "permissions" section, as it doesn't deal with permission checks, it is technically a permission and access-based API error and should probably be added under this heading, so it can easily be found via tags and guide search.

feat(permissions): add deployment cause for missing access

---

guide/creating-your-bot/creating-commands.md

This is just correcting a spelling mistake in the documentation:
* `interation` should be `interaction`.

Typo correction: interation -> interaction

---

guide/voice/voice-connections.md

**Please describe the changes this PR makes:**
This PR adds a quick message to the warning area of the "Playing Audio" header in the Voice Connections page to specify that the GUILD_VOICE_STATES gateway intent is required to play audio. 
**Please describe why this PR should be merged:**
I think this PR should be merged as this would solve some confusion in the future. I had this problem for a while until finding this Reddit post: https://www.reddit.com/r/Discordjs/comments/pprpit/voice_connection_stuck_in_the_signalling_state/

Specify GUILD_VOICE_STATES intent requirement

---

guide/popular-topics/threads.md

The `code` tag wasn't being displayed here:
Manually writing out `<code>...</code>` fixed this:

fix(threads): Stylise in markdown

---

guide/popular-topics/permissions.md

Example code uses `FLAGS.VIEW_CHANNELS` instead of `FLAGS.VIEW_CHANNEL`, where the property VIEW_CHANNELS from Permissions.FLAGS is nonexistent.

Fix code example on Permissions

---

guide/popular-topics/faq.md

Fetches user from API if user isn't present in cache.
Resolves #961.

fix(faq): Retrieve the user with `.fetch()` instead.

---

guide/interactions/slash-command-permissions.md

[`<ApplicationCommandManager>#fetch()`](https://discord.js.org/#/docs/main/main/class/ApplicationCommandManager?scrollTo=fetch) returns a Promise

fix(slash-command-permissions): missing await

---

guide/popular-topics/permissions-extended.md

This is just a small PR to add in the `MANAGE_THREADS` permission and rename `MANAGE_EMOJIS` to `MANAGE_EMOJIS_AND_STICKERS` in the elevated permissions section of the permissions-extended page.

chore(permissions-extended): Add in missing elevated permissions

---

guide/popular-topics/embeds.md

`MessageEmbed#setFooter()` now takes a sole object.

chore: Update `.setFooter()` usage

---

guide/preparations/README.md

> Download the latest version the Node.js website...
This does not makes sense as you can't download the latest version of *the node.js* **website**, while its clear that its nodejs which is to be installed here, adding a from just makes more sense and is also used above in the installation section for windows.
> ...Download the latest version **from** the Node.js website, open the downloaded file, and follow the steps from the installer.

fix: small grammer mistake

---

code-samples/.eslintrc.js
code-samples/creating-your-bot/command-handling/deploy-commands.js
code-samples/creating-your-bot/command-handling/index.js
code-samples/creating-your-bot/event-handling/index.js
code-samples/popular-topics/permissions/13/index.js
guide/.eslintrc.js
guide/creating-your-bot/command-handling.md
guide/interactions/buttons.md
guide/interactions/registering-slash-commands.md
guide/interactions/replying-to-slash-commands.md
guide/interactions/select-menus.md
guide/voice/audio-resources.md

Use the `node:` protocol in all the `require()` calls that import a built-in node module.
I found all imports of fs, util and path, let me know if you find some other imported node module...

refactor: use the `node:` protocol

---

guide/popular-topics/permissions-extended.md

Trying to moderate a `GuildMember` with `ADMINISTRATOR` permission rejects with `Missing Permissions`
(https://github.com/discord/discord-api-docs/pull/4390 for reference)
Not too sure about the wording: timeout / disableCommunicationUntil / moderate

feat(perm-ext): timeout member with administrator

---

guide/popular-topics/faq.md

Since uncached presences would make `member.presence` return `null` i think this bit should be modified to use optional chaining and deal with that to avoid accessing null

feat(faq): use optional chaining to access status

---

README.md
guide/.vuepress/config.ts
guide/creating-your-bot/creating-commands.md
guide/miscellaneous/parsing-mention-arguments.md

The main site ([discord.js.org](https://discord.js.org)) uses lowercase discord.js, and so does the server. This pull request changes all "Discord.js" instances to "discord.js". I have no idea if this is going to break anything as getting up a local version didn't work for me, so the deploy preview is my friend :D
Deploy Preview: https://deploy-preview-1015--discordjs-guide.netlify.app/
Update: I think everything worked! 🎉

refactor: use lowercase discord.js everywhere

---

guide/miscellaneous/parsing-mention-arguments.md

fixes USERS_PATTERN regex return
This expression
```ts
const matches = mention.match(USERS_PATTERN);
```
may return the match without the actual id. This might cause confusion, as `matches[1]` does not exist.
We need to `exec` on that regex to include the capture groups: 
```ts
USERS_PATTERN.exec(mention)
```
which always returns the id found, if any

fix(misc): make parsing mention arguments more resilient

---

guide/sequelize/README.md

The `'` must be escaped here as the string is enclosed between it so it must be escaped, an alternative is to make it "does not"

fix: typo by escaping character

---

guide/popular-topics/audit-logs.md

Updated `guildMemberLeave` to `guildMemberRemove` (seen [here](https://discordjs.guide/popular-topics/audit-logs.html#some-quick-background) in the guide), as that event is outdated.

Change "guildMemberLeave" to "guildMemberRemove"

---

guide/interactions/buttons.md

This changes this warning's usage of `custom_id` to `customId` for consistency. 
`custom_id` might no longer exist too, but I'm not sure about that and this should be changed regardless.

Change button "custom_id" to "customId"

---

guide/popular-topics/partials.md

The TypeScript types for v13 have `GUILD_SCHEDULED_EVENT` (https://github.com/discordjs/discord.js/blob/dfea9c27cef4ec7472c39675c93de985b43fee87/typings/index.d.ts#L5403) which was missing from the docs.

Add GUILD_SCHEDULED_EVENT to list of partials

---

code-samples/popular-topics/canvas/13/index.js
guide/popular-topics/canvas.md

[@napi-rs/canvas](https://www.npmjs.com/package/@napi-rs/canvas) is similar to canvas but does not rely on postinstallation scripts (no node-gyp!!) which makes it much more useful for new developers or basically anyone that has ever tried debugging why a node-gyp error occurs. It supplies the same canvas api, along with some non-spec compliant apis such as `canvas.toBuffer(?mimeType)` that `canvas` has.
I'm unsure if this change is wanted but not having to deal with node-gyp anymore seems like a huge win IMO. 👍 
- No post installation script, no build tools needed, etc...
- Less dependencies (faster start up for beginners, less time installing packages)
- Faster (doubt this really matters as this guide is aimed at …

feat: replace 'canvas' with '@napi-rs/canvas'

---

guide/interactions/slash-commands.md

This adds the attachment option to the guide. I noticed the `NUMBER` option was not in order like the other options, so I corrected that too.

feat(Interactions): Add attachment option

---

guide/interactions/slash-commands.md

This PR updates the choices section to the latest builders release, as `addChoice` was removed.

fix: Choices

---

guide/interactions/slash-commands.md

Global commands used to take an hour to roll out, but have been changed to roll out instantly so this tip no longer applies.

fix(slash): globals don't take an hour to roll out

---

guide/interactions/autocomplete.md

The return type of AutocompleteInteraction#respond is void, this PR removes the response variable and no longer awaits the promise, hence also making the function synchronous.

feat(autocomplete): remove `response` variable

---

guide/oauth2/README.md

The syntax for the code group located in the [OAuth2](https://discordjs.guide/oauth2/) guide was malformed which led to the rest of the page not being loaded.
This pull request resolves #1167.

Correct code group syntax in OAuth2 Page

---

guide/interactions/buttons.md

I have edited the following code from [this article](https://discordjs.guide/interactions/buttons.html#updating-the-button-message):
```js
const filter = i => i.customId === 'primary' && i.user.id === '122157285790187530';
const collector = interaction.channel.createMessageComponentCollector({ filter, time: 15000 });
collector.on('collect', async i => {
if (i.customId === 'primary') {
await i.update({ content: 'A button was clicked!', components: [] });
}
});
```
When creating the collector, the `filter` function was used, because of which the collector will only collect components whose `customId` is `'primary'`. Therefore, the additional check `if (i.customId === 'primary')` is useless here.

Useless part of the code was removed

---

guide/miscellaneous/useful-packages.md

In the tutorial of [pino-pretty](https://discordjs.guide/miscellaneous/useful-packages.html#pino) example script, it sets the custom time format `yyyy-mm-dd HH:MM:ss`, but as the argument value contains space so the output will only shows the date.
This PR adds quotes around the value to apply the expected format.

fix(useful-packages): fix pino-pretty script example

---

guide/additional-info/changes-in-v14.md

Unsafe builders got removed a while ago
- discordjs/discord.js#8074

change unsafe builders to disable/enableValidators

---

guide/additional-info/changes-in-v14.md

Fix minor typo; rename `ThreadMembersUpdate` event to `threadMembersUpdate`. Prevents any misunderstandings.

Fix ThreadMembersUpdate typo

---

guide/additional-info/changes-in-v13.md
guide/preparations/README.md
guide/sequelize/README.md

When browsing https://v13.discordjs.guide/, installing should only cover version 13.

refactor: Ensure version 13 guide only installs version 13

---

guide/popular-topics/faq.md

I believe the guide is trying to convey that you can mention users by formatting their Ids in a certain way, currently this method is incomplete.
Interestingly, this typo dates back to the [v11](https://v12.discordjs.guide/popular-topics/faq.html#how-do-i-mention-a-specific-user-in-a-message) guide.

fix(mention-user-by-Id)

---

guide/additional-info/changes-in-v14.md

Following https://github.com/discordjs/discord.js/pull/8052, the migration guide does not mention that the functions in `Util` are now top level exports

Mention Util change

---

guide/popular-topics/faq.md

Ironically, #1197 was incorrect too. I missed the `$` completing the template literal.

fix(faq): $ in template literal

---

guide/popular-topics/canvas.md

**[@napi-rs/canvas](https://npm.im/@napi-rs/canvas)** supports the `loadImage` function since v0.1.25
and it is a lot easier to load image via `loadImage`:
```diff
- const imgData = getBufferSomehow(source);
- const image = new Canvas.Image();
- image.src = imgData;
- ctx.drawImage(image, ...);
+ const image = await Canvas.loadImage(source);
+ ctx.drawImage(image, ...)
```
`loadImage` function supports file path, url, data uri, streams, `Image` and buffer-like objects.
Edit:
I have replaced `canvas.toBuffer('image/png')` with `await canvas.encode('png')` because the `encode` method does the processing in a separate thread, without blocking the main event loop.

Update canvas guide to use loadImage

---

guide/popular-topics/embeds.md

On https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object, the raw API data for the embed is not in an ISO 8601 format. This pull request modifies that.

fix(Embeds): Use raw embed timestamp

---

guide/popular-topics/permissions.md

This PR fixed a typo that's barely noticeable. As of the making of this PR, there is no permission flag named `ViewChannels`, as per what was previously stated in this section. It is most likely that the intended permission flag is `ViewChannel` (singular). This PR should be merged to avoid confusing readers with code that directly contradicts a previous statement made in the guide.

typo(permissions): Fix Permission flag typo

---

guide/keyv/README.md

Keyv has become a monorepo, their readme for their main package has shifted file locations.

fix: outdated anchor link

---

guide/interactions/autocomplete.md

Change autocomplete documentation to inform readers that the maximum number of choices they can respond with is 25. 
As a user myself, I faced issues with the implementation of my bot because I assumed the limit would be higher.
I could not find this limit detailed in the discord documentation, but discord.js replies with an detailed error when you send more than 25 options:
```
DiscordAPIError[50035]: Invalid Form Body
data.choices[BASE_TYPE_MAX_LENGTH]: Must be 25 or fewer in length.
```
Please feel free to suggest grammar/wording improvements, as I am not a native English speaker.

Add autocomplete choice limit (25) to documentation

---

guide/additional-info/changes-in-v14.md

https://github.com/discordjs/discord.js/pull/7076 removed ClientOptions#restWsBridgeTimeout, but this was previously not mentioned in the v13->v14 upgrade guide. This PR adds it.

Mention `restWsBridgeTimeout` in the v14 upgrade documentation

---

guide/popular-topics/faq.md

The original section for "How do I unban a user?" uses `<CommandInteractionOptionResolver>.get(...).value` instead of `<CommandInteractionOptionResolver>.getUser(...)` which is inconsistent with the nearby section regarding banning users.  This corrects that, and it rewrites the tip that was originally based on message commands instead of slash commands.

refactor(faq): use consistent examples

---

guide/.vuepress/config.ts

<https://discord.js.org/#/docs/main/stable/general/welcome> (Should be main, not stable)
> Jiralite suggested be changed to `https://discord.js.org/#/`

fix(navbar): documentation pointing to stable in v14

---

guide/creating-your-bot/event-handling.md

The commands folder and deploying-commands.js file from the previous section, Command Handling, were not listed.

chore(eventhandling): add to project directory list

---

guide/additional-info/changes-in-v14.md

It would be good to mention the `Modal` -> `ModalBuilder` change in the migration guide

Add note about Modal being renamed to ModalBuilder

---

guide/additional-info/changes-in-v13.md
guide/additional-info/changes-in-v14.md

`deleteMessageDays` is deprecated. Users should be using `deleteMessageSeconds` instead: https://github.com/discordjs/discord.js/pull/8326.

chore: Mention deleteMessageSeconds instead of deleteMessageDays

---

guide/popular-topics/faq.md

The forum example is using an invalid property, `tags`. It's called `appliedTags`.

fix: forum example

---

guide/additional-info/changes-in-v14.md

This tripped me up for a few hours; the v14 discord API wasn't complaining that I was using `"BUTTON"` over `ComponentType.Button` like it would when I used `"PRIMARY"` over `ButtonStyle.Primary`. I feel like this could save others some time! Thanks.

Warn users of change from component collector `"BUTTON"` to `ComponentType.Button`

---

guide/.vuepress/components/DocsLink.vue

As guide is v14 but docs still use stable
> Example issue #1278

DocsLink use main branch as default

---

guide/popular-topics/embeds.md

Description: The word "ten" should be spelled out in the last bullet of the "Embed Limits" page section since the section uses numbers frequently in the other bullet points.
Explanation: I believe that the original writer was following the rule where whole numbers from one to ten, but there's another rule that consistency is more important and overrides all other rules[^1]. This rule should only be applied to this specific case because the other numbers in the "Embed Limits" section are written using numerical representation, making the "ten" stand out awkwardly.
[^1]: https://www.scribendi.com/academy/articles/when_to_spell_out_numbers_in_writing.en.html

Numbers: Numerical vs written representation

---

guide/improving-dev-environment/package-json-scripts.md
guide/preparations/README.md

Fixes invalid command for `pnpm` initialization. Unlike `npm` and `yarn` that uses a `-y` flag to skip answering `package.json` config options, `pnpm` does that by default. Using a `-y` flag causes an error.

fix invalid pnpm init command

---

code-samples/oauth/simple-oauth-webserver/index.js
guide/oauth2/README.md

Resolves issue [#1172](https://github.com/discordjs/guide/issues/1172#issue-1306814581) in which the OAuth2 guide has a request body that is neither a string or buffer object

fix(Oauth2): set request body to string

---

guide/popular-topics/permissions-extended.md

Resolves issue [#959](https://github.com/discordjs/guide/issues/959) by adding the bot being timed out as a cause for DiscordAPIError 50001

feat: add bot timeout missing access

---

guide/popular-topics/faq.md

Adds [GuildMember#timeout()](https://discord.js.org/#/docs/discord.js/main/class/GuildMember?scrollTo=timeout) to the FAQs administrative section

feat(faq): add member timeout

---

guide/interactions/select-menus.md

Addresses issue #1318 by adding a rudimentary section for accessing [SelectMenuInteraction#values](https://discord.js.org/#/docs/discord.js/main/class/SelectMenuInteraction?scrollTo=values) upon receiving a select menu interaction in the style of the guides

feat(select-menus): add access select menu values

---

guide/popular-topics/permissions.md

Rename `Permissions` to `PermissionsBitField`

fix(Permissions): use correct name for constructor

---

guide/slash-commands/response-methods.md

The Response message for "Ephemeral responses" is showing as "Pong!" when it should be showing as "Secret Pong!"

Correct the response for "Ephemeral responses"

---

guide/slash-commands/permissions.md

The "button components section" link has a self-reference to the current page due to an empty URL reference. Added a reference to /interactions/buttons.html.

Add correct link to Buttons page

---

guide/creating-your-bot/command-deployment.md

can't have a trailing comma in JSON

removed trailing comma in example config.json

---

guide/interactions/buttons.md
guide/interactions/modals.md

Add the definition for `Events` in code examples

fix: define `Events` in code examples

---

guide/additional-info/changes-in-v14.md
guide/interactions/modals.md
guide/interactions/select-menus.md

`BaseInteraction#isSelectMenu()` => `BaseInteraction#isStringSelectMenu()`
`SelectMenuBuilder` => `StringSelectMenuBuilder`
`SelectMenuInteraction` => `StringSelectMenuInteraction`

fix: rename SelectMenu to StringSelectMenu

---

guide/popular-topics/threads.md

Here my PR my issue to fix #1367
`GuildTextThreadManager` should be used instead of `ThreadManager`

Fix DocsLink path for threads page

---

guide/popular-topics/intents.md

It is often advised that users do not use a number for intents. This is because users often use a number to represent "all intents", not realizing the number gets outdated with the introduction of other intents. The majority of people who are reading the guide at this point would benefit from listing out all their intents as strings/enums not only for readability, but for debugging purposes as well. This would help people figure out why they aren't collecting certain data, things they are missing, etc. I feel the blurb about bitfields directly under this code example is more than sufficient. The problem with having a code example is blind copy pastes, and there is no good reason to include it.
tldr: intent number …

Removal of Number Intent Example

---

guide/popular-topics/collectors.md

`ComponentType.SelectMenu` has been deprecated when Discord released new type of select menus.

fix: rename SelectMenu to StringSelect

---

guide/voice/README.md

Adds the sodium-native encryption package as an option under extra dependencies for encryption libraries. This should be merged as sodium-native is a good and fast encryption library which is supported within @discordjs/voice and is easy to install.

feat(voice): Add sodium-native encryption package

---

code-samples/creating-your-bot/command-deployment/index.js
code-samples/creating-your-bot/command-handling/index.js
guide/creating-your-bot/command-handling.md
guide/popular-topics/faq.md

This PR simply updates the way errors are displayed following the command handler guide. In cases where one has already replied to the interaction and an individual command file code errors after the reply, this error reply does not work. This can be solved with a simple check to see if the interaction is deferred or replied.

Update Command Error Handling

---

guide/interactions/context-menus.md

* Specifies the `builders` docs section for `ContextMenuCommandBuilder`.
* Updates the classes from `UserContextMenuInteraction` and `MessageContextMenuInteraction` to `UserContextMenuCommandInteraction` and `MessageContextMenuCommandInteraction`, respectively.

Fix context menu documentation links

---

guide/creating-your-bot/command-handling.md

After #1337 the command handler has more lines to highlight.

fix(executing-commands): highlight whole handler

---

guide/additional-info/changes-in-v14.md

`Client#rest` had no `request` event. Instead, Diagnostic Channels should be used.

fix(changes-in-v14): Use Diagnostics Channel

---

guide/.vuepress/components/DocsLink.vue

Recently merged PR #1435 added sections for [discordjs.dev/docs/packages](https://discordjs.dev/docs/packages). This PR adds the `util` section since that was left out.

chore: add util section

---

code-samples/creating-your-bot/command-deployment/deploy-commands.js
guide/creating-your-bot/command-deployment.md
guide/slash-commands/deleting-commands.md

We should keep the default version set by the lib instead of setting it by ourselves.
Also, when upgrading to a major version, people often don't update the version too.

refactor(commands): do not specify the version option for REST

---

code-samples/creating-your-bot/command-deployment/deploy-commands.js
code-samples/creating-your-bot/event-handling/index.js
guide/creating-your-bot/command-deployment.md
guide/creating-your-bot/command-handling.md
guide/creating-your-bot/event-handling.md
guide/creating-your-bot/slash-commands.md
guide/slash-commands/response-methods.md

This is an attempt to address some common errors seen in support from people who are following the guide (or not following it fully as the case usually is).
This adds an identical tip box to each of the slash command pages that need to be completed in conjunction with each other before the commands will be fully functional (write the commands + load/handle the commands + deploy the commands). People often miss one or more of these steps.
This also makes some changes to the event handling guide to attempt to improve the transition from the other pages. I noticed that our code sample for event handling didn't include the code for command loading. As people don't read and just copy and paste code snippets, it's been added back to the samples to reduce the support load of having to explain …

feat: further improvements to the Creating your bot section

---

guide/creating-your-bot/command-deployment.md

Hi! I'm going through the examples from scratch and ran into a few issues above:
- `foldersPath` was undefined
- I moved the REST() into the async, otherwise I got `TypeError: (intermediate value).setToken(...) is not a function`
I'm using Node 18.15.0 on Windows 11. After the above changes, the tutorial works again

fix(command-deployment): folder pathing variable fix

---

guide/message-components/interactions.md

Originally, the collector acknowledged `i`, the interaction instance only defined in the scope of the filter function.  Now, it acknowledges `confirmation`, the interaction instance that was actually collected.

fix(interactions): use correct interaction

---

code-samples/popular-topics/reactions/14/awaiting-reactions.js
guide/additional-info/changes-in-v13.md
guide/additional-info/changes-in-v14.md
guide/additional-info/es6-syntax.md
guide/message-components/interactions.md
guide/popular-topics/collectors.md
guide/popular-topics/faq.md
guide/popular-topics/reactions.md

I think it's better to name the `filter` variable differently than the `filter` option because people are often thinking that they could name the variable however they want and pass it as a key in the method.

refactor(collectors): rename the filter variable

---

code-samples/additional-features/reloading-commands/commands/fun/ping.js
code-samples/additional-features/reloading-commands/commands/moderation/kick.js
code-samples/additional-features/reloading-commands/commands/moderation/prune.js
code-samples/additional-features/reloading-commands/commands/utility/avatar.js
code-samples/additional-features/reloading-commands/commands/utility/reload.js
code-samples/additional-features/reloading-commands/commands/utility/server.js
code-samples/additional-features/reloading-commands/commands/utility/user.js

For the reloading commands part of the code, it failed to run if the commands were in categories as suggested previously by the guide thus the code couldn't get the commands through require. I added a category key to the exports object and appropriate code in the reload.js file to properly.

fix(reloading-commands): add categories to code samples

---

guide/additional-info/changes-in-v13.md
guide/creating-your-bot/command-deployment.md
guide/slash-commands/permissions.md
guide/whats-new.md

Just a small change to prevent 404, I updated 2 links from `/interactions` to `/message-components`.

fix(*): Update message component links to no longer 404

---

code-samples/additional-features/cooldowns/commands/utility/avatar.js
code-samples/additional-features/reloading-commands/commands/utility/avatar.js
code-samples/creating-your-bot/command-handling/commands/utility/avatar.js

This property doesn't exist in v14 and having it in the code sample that's referenced in the guide may lead to some confusion.

fix: remove `dynamic: true` in code samples

---

guide/message-components/interactions.md

This fixes an invalid link which would take you to https://discordjs.guide/message-components/creating-your-bot/event-handling which doesn't exist, it should be https://discordjs.guide/creating-your-bot/event-handling

fix(interactions): invalid link to event handling in component interactions

---

guide/additional-info/async-await.md

As discussed internally, just throwing an error can sometimes lead to it never actually being thrown with a never resolving promise. So the promise should be rejected instead.

fix(additional-info): reject promise instead of throwing an error

---

guide/additional-info/es6-syntax.md

I rearranged the username and password line in the ES6 example to match exactly the ES5 example. Then people won't get confused.
You can look at https://discordjs.guide/additional-info/es6-syntax.html#template-literals-vs-string-concatenation to see for yourself what it looks like currently.

fix(es6-syntax): rearrange username and password for consistency

---

CONTRIBUTING.md
code-samples/additional-features/cooldowns/index.js
code-samples/additional-info/rest-api/14/index.js
code-samples/creating-your-bot/command-deployment/index.js
code-samples/creating-your-bot/command-handling/index.js
code-samples/creating-your-bot/initial-files/index.js
code-samples/creating-your-bot/slash-commands/index.js
code-samples/keyv/index.js
code-samples/popular-topics/canvas/14/index.js
code-samples/popular-topics/permissions/14/index.js
code-samples/popular-topics/reactions/14/awaiting-reactions.js
code-samples/popular-topics/reactions/14/basic-reacting.js
code-samples/popular-topics/reactions/14/uncached-messages.js
code-samples/sequelize/tags/sequelize.js
guide/additional-info/rest-api.md
guide/creating-your-bot/event-handling.md
guide/creating-your-bot/main-file.md
guide/popular-topics/canvas.md
guide/popular-topics/reactions.md
guide/sequelize/README.md
guide/sequelize/currency.md

Per https://github.com/discordjs/guide/pull/1525#pullrequestreview-1747094664, this event has been standardised everywhere it should be in the guide.
The first instance of this when following the guide is at guide/creating-your-bot/main-file.md. There were some code comments already, so I appended why this is useful for TypeScript users.

refactor: Standardise `ClientReady` event

---

guide/message-components/select-menus.md

Pretty simple grammar fix. The current one would expand to this if you removed the contraction:
"Although the String select menu with it is user-defined options..."

fix(select-menus): Improper "it's" contraction

---

guide/message-components/interactions.md

Fixed contraction error when referring to the reader's event handling.

fix(interactions): Improper "you're" contraction

---

guide/miscellaneous/cache-customization.md

Using client while constructing it leads to it being of type `any` instead of `Client<boolean>`. Accessing it from the callback parameter fixes this.

fix(cache-customization): Access `client` from callback parameter

---

guide/popular-topics/formatters.md

Replaced the deprecated `underscore` formatter with `underline`

fix(popular-topics): replace deprecated `underscore` with `underline`

---

guide/additional-info/updating-from-v14.md

A typo has been fixed.
`devoration` -> `decoration`

fix(updating-from-v14): "decoration" typo

---

guide/slash-commands/parsing-options.md
guide/slash-commands/permissions.md

Replaces information about deprecated `SlashCommandBuilder#setDMPermission` with `SlashCommandBuilder#setContexts`

chore(slash-commands): replace `setDMPermission` with `setContexts`

---

guide/slash-commands/autocomplete.md

Updates `getFocused()` usage as the boolean parameter has been removed (the full object is always returned).

refactor(autocomplete): Update `getFocused()` section

---

guide/additional-info/updating-from-v14.md

Replaced `BaseInteraction#isAnySelectMenu()` with `BaseInteraction#isSelectMenu()`

refactor(additional-info): replace `isAnySelectMenu` with `isSelectMenu`

---

code-samples/popular-topics/reactions/14/awaiting-reactions.js
code-samples/popular-topics/reactions/14/basic-reacting.js
guide/additional-info/async-await.md
guide/additional-info/changes-in-v14.md
guide/popular-topics/collectors.md
guide/popular-topics/faq.md
guide/popular-topics/reactions.md
guide/slash-commands/response-methods.md

- https://github.com/discordjs/discord.js/pull/10636

refactor: Use `withResponse`

---

guide/miscellaneous/useful-packages.md

Corrected past tense 'you got' to present tense 'you've got'.

fix(useful-packages): Minor typo
